import LocalizedStrings from 'react-localization';

export const strings = new LocalizedStrings({
  en: {
    // ingame messages
    ok : "Ok",
    cancel : "Cancel",
    close : "Close",
    save : "Save",
    reset : "Reset",
    overview : "villages overview",
    svers : "script version",
    settings : "settings",
    notes : "notes",
    res90 : "resources to % filling",
    refresh : "refresh",
    warehouse : "Warehouse",
    resources : "Resources",
    troops : "Troops",
    links : "Links",
    linkname : "link name",
    linkdel : "delete link",
    name2 : "second name",
    archive : "Archive",
    arena : "Tournament Square",
    addcur : "add current",
    del : "Delete",
    edit : "edit",
    unpin : "unpin",
    pin : "pin",
    total : "Total",
    noplace : "There is no place!",
    hunger : "hunger",
    duration : "duration",
    deficit : "deficit",
    aclock : "Alarm clock\nhh:mm:ss , hh:mm , mm (from now)",
    consnegat : "Crop consumption in this village is negative. How many minutes needed reserve?",
    bmove : "Move buildings",
    neighbors : "neighbors",
    cargo: "Cargo",
    defense: "Defense",
    // settings
    auctions: "Auctions",
    none : "None",
    auto : "auto",
    info : "Information",
    yourrace : "Your tribe",
    sspeed : "Server speed",
    sspeedh : "0 - auto, 1 (1x), 2 (2x), 3 (3x aka speed), ... etc.",
    servertype : "Travian Server Type",
    servertypeh : "Server types: Travian Legends, Travian Shadow Empires",
    servertypeo : ['update','Shadow Empires','Legends'],
    speedart : "Speed artefact",
    racelist : ['Romans','Teutons','Gauls','Nature','Natars','Egyptians','Huns','detect'],
    cranny : "Yellow level of cranny (percent)",
    crannyh : 'normal 80, 70 for classic or artefact plunder',
    builtin : "Built-in tools",
    builtinh : 'red color - most needed resources, green - less needed resources',
    normalize : 'Normalize production',
    normal : "normal",
    banalyze : "Built-in battle analyzer",
    cropfind : "Built-in crop finder",
    adetect : "Attack detector",
    adetecto : ['off','w/o freeze','on'],
    adetecth : "makes hidden requests to the server, violating the rules. may result in punishment.",
    adetectt : "Period of attack detect",
    adetectth : "The first check is always after 5 minutes. Next checks will be after the configured time period.",
    buildhint : "Construction tips",
    onallp : "All pages",
    buildand : "Show building countdown and attack",
    buildandh : 'In the list of villages',
    buildands : ['off','on','wide'],
    sendres : "Show &laquo;send resource/troops&raquo; icons",
    sendmess : "Show &laquo;send message&raquo; icons",
    analyzer : "World analyzer",
    bigicon : "Show Rally Point icon",
    addvtable : "Show additional village table",
    addvtableo : ['off','on','stick'],
    opennote : "Automatically open Notes window",
    notesize : "Size of Notes window",
    openoview : "Automatically open villages overview",
    resbar : "Resource bar",
    showres : "Show resource bar in window",
    redbl : "red (in hours)",
    yellowbl: "yellow (in hours)",
    marketpl : "Marketplace",
    npcsum : "Summary for NPC",
    npcsumh : 'in marketplace and buildings',
    bidinc : "Auctions bid increment",
    bidinch : 'Put a value of 0 to disable the function',
    show3x : "Predict the flow of resources at sending with 2x and 3x",
    show3xh : 'may show incorrect data',
    rpandmp : "Rally Point and Marketplace",
    incomres : "Incoming resources info",
    incomreso : ['off','on','with summary','WW mode'],
    troopsI : "Information about troops",
    troopsIo : ['off','on','update'],
    defRP : "Default action for rally point",
    showls : "Show links",
    showAsSN : "Use links as second name",
    showlso : ['off','on','in window'],
    savedls : "Saved links",
    savedd : "Saved data",
    saveddh : 'including Links and Second name. If an Account deleted, or not your computer.',
    savedelall : "Delete all saved data",
    savedelallh : 'Are you sure you want to delete all data, including the links and the second name?',
    scrlang : "Script language",
    youlang : "Browser language",
    notifi : "Notification",
    notification : "notification after construction",
    method : "Method",
    audiourl : "URL of audio file",
    audiotest : "Audio test",
    colorCustomize : "Color options",
    colorHint : "leave empty for the default colors",
    color0 : "Upgrade available",
    color1 : "Upgrade via NPC",
    color2 : "Upgrade not possible <br/>(not enough resources)",
    color3 : "Upgrade not possible <br/>(not enough capacity of granaries/warehouses)",
    color4 : "Final level"
  },
  ru: {
    // ссобщения в игре
    cancel : "Отмена",
    close : "Закрыть",
    overview : "обзор деревень",
    svers : "версия скрипта",
    settings : "настройки",
    notes : "заметки",
    res90 : "к % заполнения склада",
    refresh : "обновить",
    warehouse : "Склады",
    resources : "Запасы",
    troops : "Войска",
    links : "Ссылки",
    linkname : "название ссылки",
    linkdel : "удалить ссылку",
    name2 : "второе имя",
    archive : "Архив",
    arena : "Арена",
    addcur : "добавить эту деревню",
    del : "удалить",
    edit : "изменить",
    unpin : "открепить",
    pin : "закрепить",
    total : "Всего",
    noplace : "Нет места!",
    hunger : "наступление голода",
    duration : "продолжительность",
    deficit : "дефицит",
    consnegat : "Потребление в этой деревне отрицательное. На сколько минут нужен запас?",
    bmove : "Перемещение зданий",
    neighbors : "соседи",
    cargo: "Доставка",
    defense: "Подкрепление",
    // настройки
    auctions: "Аукцион",
    none : 'нет',
    auto : "авто.",
    info : "Общая информация",
    yourrace : "Ваш народ",
    sspeed : "Скорость сервера",
    sspeedh : "0 - авто, 1 (1x), 2 (2x), 3 (3x или скоростной), ...",
    speedart : "Артефакт скорости",
    racelist : ['Римляне','Германцы','Галлы','Nature','Натары','Египтяне','Гунны','detect'],
    cranny : "желтый уровень занятости тайника (проценты)",
    crannyh : 'норма - 80, 70 для классического сервера или для артефакта грабителя',
    builtin : "Встроенные инструменты",
    builtinh : 'для нормального производства: красный цвет - самый необходимый ресурс, зелёный - лишнее производство',
    normalize : 'Нормальное производство',
    normal : "ресурсы",
    banalyze : "Встроенный анализатор боя",
    cropfind : "Встроенный поиск свободных хлебных клеток",
    adetect : "Обнаружение нападения",
    adetecto : ['выкл.','без заморозки','включено'],
    adetecth : "делает скрытые обращения к серверу, нарушая правила. может повлечь наказание.",
    adetectt : "период обнаружения",
    buildhint : "Подсказки возможности строительсва",
    onallp : "На всех страничках",
    buildand : "Показывать таймер построек и атаки",
    buildandh : 'отображается как часики в списке деревень',
    buildands : ['нет','да','широкий'],
    sendres : "Показывать иконки &laquo;отослать ресурсы/войска&raquo;",
    sendmess : "Показывать иконки &laquo;отослать сообщение&raquo;",
    analyzer : "Анализатор мира",
    bigicon : "Показывать Пункт сбора икон",
    addvtable : "Показывать дополнительную таблицу деревень",
    addvtableo : ['нет','да','приклеить'],
    opennote : "Автоматически открывать заметки",
    notesize : "Размер окна заметок",
    openoview : "Автоматически открывать обзор деревень",
    resbar : "Таблица ресурсов",
    showres : "Показывать таблицу ресурсов в окне",
    redbl : "красный (в часах)",
    yellowbl: "желтый (в часах)",
    marketpl : "Рынок",
    npcsum : "сумма ресурсов для NPC",
    npcsumh : 'на рынке и стройках',
    bidinc : "шаг ставки",
    bidinch : 'для аукционов травиан версии 4',
    show3x : "показывать возможно неверные данные",
    show3xh : 'попытка предсказать поступление ресурсов при 3x и 2x отправке',
    rpandmp : "Пункт сбора и рынок",
    incomres : "информация о поступающих ресурсах",
    incomreso : ['нет','есть','с итогами','Чудо режим'],
    troopsI : "Информация о войсках",
    troopsIo : ['нет','да','обновить'],
    defRP : "действие по умолчанию для пункта сбора",
    showls : "Показывать ссылки",
    showAsSN : "Использовать ссылки как второе имя",
    showlso : ['нет','да','в окне'],
    savedls : "сохранённые ссылки",
    savedd : "сохранённые данные",
    saveddh : 'включая Ссылки и Второе имя деревень. Если учетная запись удаляется или это не ваш компьютер.',
    savedelall : "удалить все данные",
    savedelallh : 'Вы уверены, что хотите удалить все данные, включая Ссылки и Второе имя деревень?',
    scrlang : "Язык скрипта",
    youlang : "Ваш язык",
    notifi : "напоминания",
    notification : "оповищение после строительства",
    method : "метод",
    audiourl : "URL звукового файла",
    audiotest : "проверить звук",
    colorCustomize : "Настройки цвета",
    colorHint : "оставьте пустым для цвета по умолчанию",
    color0 : "развитие возможно",
    color1 : "развитие возможно с NPC",
    color2 : "развитие невозможно <br/>(недостаточно ресурсов)",
    color3 : "развитие невозможно <br/>(недостаточная вместимость склада/амбара)",
    color4 : "максимальный уровень"
  },
  ua: { fb : "ru",
    cancel : "Скасувати",
    close : "Закрити",
    overview : "огляд поселень",
    svers : "версія скріпта",
    settings : "налаштування",
    notes : "нотатки",
    res90 : "к % заповнення складу",
    refresh : "Оновити",
    warehouse : "Склади",
    resources : "Запаси",
    troops : "Війська",
    links : "Посилання",
    linkname : "назва посилання",
    linkdel : "видалити посилання",
    name2 : "друге ім'я",
    archive : "Архів",
    addcur : "додати це поселення",
    del : "видалити",
    edit : "змінити",
    unpin : "відкріпити",
    pin : "закріпити",
    total : "Всього",
    noplace : "Нема місця!",
    hunger : "настає голод",
    duration : "тривалість",
    deficit : "дефіцит",
    consnegat : "Споживання у цьому поселенні від'ємне. На скількі хвилин потрібен запас?",
    bmove : "Переміщення будівель",
    neighbors : "сусіди",
    // настройки
    auctions: "Аукціон",
    none : 'нема',
    auto : "авто.",
    info : "Загальна інформація",
    yourrace : "Ваш народ",
    sspeed : "Швидкість сервера",
    sspeedh : "0 - авто, 1 (1x), 2 (2x), 3 (3x або швидкісний), ...",
    speedart : "Артефакт швидкості",
    racelist : ['Римляни','Тевтонці','Галли','Nature','Natars','Egyptians','Huns','detect'],
    cranny : "Жовтий рівень зайнятості схованки (проценти)",
    crannyh : 'норма - 80, 70 для класичного сервера або для артефакту злодія',
    builtin : "Вбудовані інструменти",
    builtinh : 'для нормального виробництва: червоний колір - самий необхідний ресурс, зелений - надлишкове виробництво',
    normalize : 'Нормальне виробництво',
    normal : "ресурси",
    banalyze : "Аналізатор боя",
    cropfind : "Пошук вільних хлібних клітин",
    adetect : "Виявлення нападу",
    adetecto : ['вимкнуте','без заморозки','увімкнено'],
    adetecth : "робить скриті звернення до серверу, порушуя правила. може викликати покарання.",
    adetectt : "Період виявлення",
    buildhint : "Підказки можливості будівництва",
    onallp : "На всіх сторінках",
    buildand : "Відображати таймер будівництва і атаки",
    buildandh : 'відображається як таймер у списку поселень',
    buildands : ['ні','так','широкий'],
    sendres : "Відображати іконки &laquo;відіслати ресурси/війска&raquo;",
    sendmess : "Відображати іконки &laquo;відіслати листа&raquo;",
    analyzer : "Аналізатор світу",
    bigicon : "Відображати Пункт сбора икон",
    addvtable : "Відображати додаткову таблицю поселень",
    addvtableo : ['ні','так','приклеїти'],
    opennote : "Автоматично відкривати нотатки",
    notesize : "Розмір вікна нотаток",
    openoview : "Автоматично відкривати огляд поселень",
    resbar : "Таблиця ресурсів",
    showres : "Відображати таблицю ресурсів в окні",
    redbl : "Червоний (в таймері)",
    yellowbl: "Жовтий (в таймері)",
    marketpl : "Ринок",
    npcsum : "сума ресурсів для NPC",
    npcsumh : 'На ринку та будівництвах',
    bidinc : "Крок ставки",
    bidinch : 'для аукціонів травіан версії 4',
    show3x : "Відображати можливо хибні відомості",
    show3xh : 'спроба передбачити надходженя ресурсів при 3x і 2x відсиланні',
    rpandmp : "Пункт сбору та ринок",
    incomres : "Інформація о надходжені ресурсів",
    incomreso : ['ні','так','з підсумками','Чудо режим'],
    troopsI : "Інформація по війсках",
    troopsIo : ['ні','так','оновити'],
    defRP : "Дія за замовченням для пункту сбору",
    showls : "Відображати посилання",
    showAsSN : "Використовувати посилання як друге ім’я",
    showlso : ['ні','так','в окні'],
    savedls : "збережені посилання",
    savedd : "Збережені данні",
    saveddh : 'включає Посилання і Друге ім’я поселення. Якщо обліковий запис відаляєтся або це не Ваш комп’ютер.',
    savedelall : "видалити всі данні",
    savedelallh : 'Ви впевнені, що бажаєте відалити всі данні, включаючи Посилання і Друге ім’я поселень?',
    scrlang : "Мова скрипта",
    youlang : "Ваша мова",
    notifi : "Нагадування",
    notification : "сповіщення після будівництва",
    method : "Метод",
    audiourl : "URL звукового файла",
    audiotest : "Перевірити звук",
    colorCustomize : "Налаштування кольору",
    colorHint : "залиште порожнім для кольору за замовченням",
    color0 : "Розвиток можливий",
    color1 : "Розвиток можливий с NPC",
    color2 : "Розвиток неможливий <br/>(недостатньо ресурсів)",
    color3 : "Розвиток неможливий <br/>(недостатня ємкість складу/комори)",
    color4 : "Максимальний рівень"
  },
  hu: { // Hungarian language. thx mrzed :)
    // ingame messages
    cancel : "Mégse",
    close : "Bezár",
    overview : "áttekintés",
    svers : "szkript verzó",
    settings : "beállítások",
    notes : "jegyzetek",
    res90 : "nyersanyagokat %-ig feltölteni",
    refresh : "frissít",
    warehouse : "Raktárépület",
    resources : "Nyersanyagok",
    troops : "Csapatok",
    links : "Linkek",
    linkname : "link név",
    linkdel : "link törlése",
    name2 : "második név",
    archive : "Archívum",
    arena : "Gyakorlótér",
    total : "Összesen",
    // settings
    auctions: "Árverések",
    none : "Nincs",
    info : "Információk",
    yourrace : "Nép",
    speedart : "Sebesség ereklye",
    racelist : ['Római','Germán','Gall','Nature','Natars','Egyptians','Huns','detect'],
    onallp : "Minden oldal",
    buildand : "Visszaszámlálók megjelenítése",
    buildandh : 'A faluk listájában (építkezések, csapatmozgások)',
    sendres : "Nyersanyag-/csapatküldés ikonok megjelenítése",
    sendmess : "Üzenetküldés ikonok megjelenítése",
    bigicon : "Gyülekezőtér ikon megjelenítése",
    opennote : "Jegyzetek automatikus megnyitása",
    resbar : "Nyersanyagkijelző",
    showres : "Nyersanyagkijelző külön ablakban",
    redbl : "piros (órában)",
    yellowbl: "sárga (órában)",
    marketpl : "Piactér",
    rpandmp : "Gyülekezőtér és piactér",
    incomres : "Információ az érkező nyersanyagokról",
    incomreso : ['ki','be','összefoglaló','WW mode'],
    troopsI : "Csapatinformációk",
    showls : "Linkek megjelenítése",
    showlso : ['ki','be','ablakban'],
    savedls : "Mentett linkek",
    scrlang : "Szkript nyelve",
    youlang : "Az Ön nyelve"
    //version = verzió
    //Rally point = Gyülekezőtér
  },
  fa: { // Persian, thx Reza Moghadam
    // ingame messages
    ok : "موافقم",
    cancel : "لغو",
    close : "بستن",
    overview : "مرور کلی",
    svers : "ورژن اسکریپت",
    settings : "تنظیمات",
    notes : "متن",
    res90 : "% منابع پر است",
    warehouse : "انبار",
    resources : "منابع",
    troops : "لشکریان",
    links : "لینک ها",
    archive : "آرشیو",
    arena : "میدان تمرین",
    // settings
    info : "اطلاعات",
    yourrace : "دسته ی شما",
    speedart : "سرعت مصنوعی",
    racelist : ['رومی ها','توتن ها','گل ها','Nature','Natars','Egyptians','Huns','detect'],
    onallp : "همه ی صفحات",
    buildand : "نمایش شمارش معکوس ساختمان و حمله",
    buildandh : 'در لیست روستا ها',
    sendres : "نمایش آیکون های ارسال منابع/سربازان",
    sendmess : "نمایش آیکون های ارسال پیام",
    bigicon : "نمایش آیکون اردوگاه",
    opennote : "بازشدن خودکار متن ها",
    resbar : "نوار منابع",
    showres : "نمایش نوار منابع در پنجره",
    redbl : "قرمز (در ساعت)",
    yellowbl: "زرد (در ساعت)",
    marketpl : "بازار",
    rpandmp : "اردوگاه و بازار",
    incomres : "دریافت اطلاعات منابع",
    incomreso : ['خاموش','روشن','خلاصه','WW mode'],
    showls : "نمایش لیننک ها",
    showlso : ['خاموش','روشن','در پنجره'],
    savedls : "ذخیره سازی لینک ها"
  },
  ar: { // Arabic, thx ww_start_t
    // ingame messages
    ok : "موافق",
    cancel : "إلغاء الأمر",
    close : "إغلاق",
    overview : "نظرة عامة على جميع القرى",
    svers : "أصدار السكربت",
    settings : "الأعدادات",
    notes : "دفتر الملاحظات",
    res90 : "الموارد حتى % للحد الأقصى",
    refresh : "تحديث",
    warehouse : "المخزن",
    resources : "الموارد",
    troops : "القوات",
    links : "الروابط",
    linkname : "أسم الرابط",
    linkdel : "حذف الرابط",
    name2 : "الأسم التالي",
    archive : "الأرشيف",
    arena : "ساحة البطولة",
    addcur : "أضافة",
    del : "أمسح",
    edit : "تعديل",
    unpin : "لم يتم أصلاحة",
    pin : "تم أصلاحة",
    total : "المجموع",
    noplace : "لايوجد سكن!",
    hunger : "جوع",
    duration : "المدة",
    deficit : "لايمكن",
    aclock : "المنبة\nhh:mm:ss , hh:mm , mm (من الوقت الحالي)",
    consnegat : "استهلاك القمح لهذه القرية سالب. كم دقيقة احتياطية تحتاج؟",
    bmove : "تحريك المباني",
    neighbors : "الجيران",
    // settings
    auctions: "مزادات",
    none : "لاشيء",
    auto : "آلي",
    info : "المعلومات",
    yourrace : "قبيلتك",
    speedart : "السرعة",
    racelist : ['الرومان','الجرمان','الأغريق','Nature','الناتار','الفراعنة','المغول','detect'],
    cranny : "النسبة للون الأصفر للمخبأ (النسبة)",
    crannyh : 'الأفتراضي 80, 70 للكلاسيك',
    builtin : "الأدوات-المبنية",
    builtinh : 'ألوان انتاج الموارد: اللون الأحمر - للأقل انتاج, اللون الأخضر - للأكثر انتاج',
    normalize : 'انتاج الموارد',
    normal : "الأفتراضي",
    banalyze : "مبني على - محاكي المعارك",
    cropfind : "مبني على - باحث عن القرى القمحية",
    adetect : "كاشف الهجمات(غير مستحسن)",
    adetecto : ['معطل','تعليق عند معجزة العالم','تفعيل'],
    adetecth : "يرسل طلبات مخفية الى السيرفر, يتم اختراق قوانين اللعبة. وقد يتم ايقاف حسابك.",
    adetectt : "فترة كاشف الهجوم",
    buildhint : "نصائح البناء",
    onallp : "الأدوات التي تعمل على جميع الصفحات",
    buildand : "اظهار وقت المباني والهجمات بجانب قائمة القرى ",
    buildandh : 'في قائمة القرى',
    sendres : "أظهار ايقونات ارسال موارد وقوات",
    sendmess : "عرض ايقونة ارسال رسالة بجانب كل لاعب",
    analyzer : "محلل السيرفر",
    bigicon : "أظهار قائمة نقطة التجمع",
    addvtable : "عرض جدول القرى",
    addvtableo : ['معطل','تشغيل','تعليق'],
    opennote : "فتح دفتر الملاحظات آلياً",
    notesize : "حجم دفتر الملاحظات",
    openoview : "فتح نافذه نظره عامه إلياً",
    resbar : "شريط الموارد",
    showres : "عرض شريط الموارد في نافذة متحركة",
    redbl : "اللون الأحمر (لكل ساعة)",
    yellowbl: "اللون الأصفر (لكل ساعة)",
    marketpl : "السوق",
    npcsum : "ملخص تاجر المبادلة",
    npcsumh : 'في السوق والمباني',
    bidinc : "المزايدة الحالية",
    bidinch : 'لترافيان النسخة4',
    show3x : "قد لايتم عرض البيانات بشكل صحيح",
    show3xh : 'محاول التنبؤ عند وجود كمية من الموارد عند ارسال موارد 3 مرات أو مرتين',
    rpandmp : "نقطة التجمع و السوق",
    incomres : "عرض معلومات عن الموارد القادمة",
    incomreso : ['معطل','تشغيل','مع المحلل','نمط معجزة العالم'],
    troopsI : "المعلومات حول القوات",
    troopsIo : ['معطل','تشغيل','مساعدة في البحث'],
    defRP : "الأجراء الأفتراضي لنقطة التجمع",
    showls : "عرض الروابط",
    showAsSN : "أستعمل الأسم التالي كـ الأسم الافتراضي",
    showlso : ['معطل','تشغيل','تشغيل في نافذة'],
    savedls : "الروابط المحفوظة",
    savedd : "البيانات المحفوظة",
    saveddh : 'بما في ذلك الروابط والأسم التالي. إذا حُذف الحساب, أو ليس الكمبيوتر الخاص بك.',
    savedelall : "مسح جميع البيانات المحفوظة",
    savedelallh : 'هل أنت متأكد من حذف جميع البيانات المحفوظة, بما في ذلك الروابط والأسم التالي؟',
    scrlang : "لغة السكربت",
    youlang : "لغتك",
    notifi : "الإبلاغ",
    notification : "إبلاغي عند أنتهاء المبنى من البناء",
    method : "الأسلوب",
    audiourl : "الرابط الخاص بالصوت",
    audiotest : "أختبار الصوت",
    colorCustomize : "إعدادات الألوان",
    colorHint : "أترك المربع فارغ لأختيار اللون الأساسي",
    color0 : "التطوير متاح",
    color1 : "يمكن التطوير عن طريق تاجر المبادله NPC",
    color2 : "لايمكن التطوير (لاتوجد موارد كافيه)",
    color3 : "لايمكن التطوير (يجب رفع مستوى مخزن الحبوب أو المخزن)",
    color4 : "اللون لـ أقصى مستوى للمبنى"
  },
  fr: { // French translation , thx azukae09
    // ingame messages
    ok : "Ok",
    cancel : "Annuler",
    close : "Fermer",
    overview : "Résumé",
    svers : "Version du script",
    settings : "configuration",
    notes : "notes",
    res90 : "Ressources à % de la capacité",
    refresh : "rafraichir",
    warehouse : "Entrepôt",
    resources : "Ressources",
    troops : "Troupes",
    links : "Liens",
    linkname : "nom du lien",
    linkdel : "supprimer lien",
    name2 : "deuxième nom",
    archive : "Archive",
    arena : "Place du tournoi",
    addcur : "ajouter celui présent",
    del : "supprimer",
    edit : "éditer",
    total : "Total",
    // settings
    auctions: "Enchères",
    none : 'Aucun',
    info : "Information",
    yourrace : "Votre peuple",
    speedart : "Artefact de vitesse",
    racelist : ['Romains','Germains','Gaulois','Nature','Natars','Égyptiens','Huns','detect'],
    onallp : "Toutes les pages",
    buildand : "Montrer le compte à rebours pour les constructions et les attaques",
    buildandh : 'Dans la liste des villages',
    sendres : "Afficher les icônes &laquo;envoyer ressources/troupes&raquo;",
    sendmess : "Afficher les icônes &laquo;envoyer message&raquo;",
    analyzer : "Outils et statistiques",
    bigicon : "Afficher le Place de rassemblement icône",
    opennote : "Ouvrir automatiquement les notes",
    resbar : "Barre des ressources",
    showres : "Montrer la barre des ressources dans une fenêtre",
    redbl : "Rouge (en heures)",
    yellowbl: "Jaune (en heures)",
    marketpl : "Place du marché",
    rpandmp : "Place du rassemblement et place du marché",
    incomres : "Info sur les ressources arrivant",
    incomreso : ['Non','Oui','Avec résumé','WW mode'],
    showls : "Afficher les liens",
    showlso : ['Non','Oui','Dans une fenêtre'],
    savedls : "Sauver les liens",
    scrlang : "Choix de la langue",
    youlang : "Langue du navigateur",
    noplace : "Plus de place!",
    hunger : "Faim",
    duration : "Durée",
    deficit : "Déficit",
    cranny : "Niveau jaune pour la cachette (pourcentage)",
    crannyh : 'Normal 80, 70 pour classique or artefact de pillage',
    builtin : "Outils integrés",
    builtinh : 'Pour normaliser la production; rouge ressource la plus demandée, vert, ressource la moins necessaire',
    normalize : 'Normalisation de la production',
    normal : "Normal",
    banalyze : "Analiseur intégré de bataille",
    cropfind : "Recherche intégrée de champs",
    adetect : "Detection des attaques",
    adetecto : ['off','sans freeze','on'],
    adetecth : "Fait des requetes masquées au serveur, ce qui viole les règles et peut ocasionner une sanction",
    adetectt : "Période de détection des attaques",
    addvtable : "afficher le tableau additionnel des villages",
    npcsum : "Résumé pour le marchand pnj",
    npcsumh : 'Dans les marchés et batiments',
    bidinc : "Incrément d'enchère",
    bidinch : 'Pour les enchères dans travian4',
    savedelallh : 'Etes vous sur d\'effacer les données sauvegardées (y compris les liens et le second nom)',
    notification : "Notification après construction",
    method : "Méthode",
    audiourl : "URL de fichier audio",
    audiotest : "test audio"
  },
  hr: { // Croatian translation, thx semiRocket
    // ingame messages
    ok : "U redu",
    cancel : "Odustani",
    close : "Zatvori",
    overview : "Pregled",
    svers : "Verzija skripte",
    settings : "Postavke",
    notes : "Zabilješke",
    res90 : "Resursi do % ispunjenja",
    refresh : "Osvježi",
    warehouse : "Skladište",
    resources : "Resursi",
    troops : "Vojska",
    links : "Poveznice",
    linkname : "Ime poveznice",
    linkdel : "Izbriši poveznicu",
    name2 : "Drugi naziv",
    archive : "Arhiva",
    arena : "Arena",
    addcur : "Dodaj trenutno",
    del : "Izbriši",
    edit : "Uredi",
    unpin : "Skini",
    pin : "Pričvrsti",
    total : "Ukupno",
    noplace : "Nema mjesta!",
    hunger : "glad",
    duration : "trajanje",
    deficit : "manjak",
    aclock : "Alarm \nhh:mm:ss , hh:mm , mm (unazad)",
    consnegat : "Potrošnja hrane u naselju je negativna. Koliko minuta želite pričuve?",
    bmove : "Premještanje građevina",
    neighbors : "susjedi",
    // settings
    auctions: "Aukcije",
    none : 'Ništa',
    auto : "automatsko",
    info : "Informacije",
    yourrace : "Tvoja jedinica",
    speedart : "Artefakt za brzinu",
    racelist : ['Rimljani','Teutonci','Gali','Nature','Natars','Egipćani','Huni','detect'],
    cranny : "Žuta razina žitnice (postotak)",
    crannyh : 'Normalno 80, 70 za klasične pljačke ili artefakt',
    builtin : "Ugrađeni alati",
    builtinh : 'Normalizacija produkcije: crveno najviše potrebni, a zeleno manje potrebni resursi',
    normalize : 'Normalizacija produkcije',
    normal : "Normalno",
    banalyze : "Ugrađeni analizator bitke",
    cropfind : "Ugrađena tražilica žitnih (crop) polja",
    adetect : "Detektiranje napada",
    adetecto : ['Isključeno','Bez zamrzavanja','Uključeno'],
    adetecth : "Radi skrivene zahtjeve prema poslužitelju kršeći pravila. Može dovesti do kazni.",
    adetectt : "Razdoblje detektiranja napada",
    buildhint : "Savjeti za gradnju",
    onallp : "Sve stranice",
    buildand : "Prikaži odbrojavanje izgradnje i napada",
    buildandh : 'Prikazuje se u listi naselja',
    buildands : ['Isključeno','Uključeno','Prostrano'],
    sendres : "Prikaži ikonice «šalji resurse/vojska»",
    sendmess : "Prikaži ikonicu «šalji poruku»",
    analyzer : "Analizator svijeta",
    bigicon : "Prikaži Okupljalište ikona",
    addvtable : "Prikaži dodatnu tablicu naselja",
    addvtableo : ['Isključeno','Uključeno','Zalijepljeno'],
    opennote : "Automatski otvori zabilješke",
    notesize : "Veličina prozora za zabilješke",
    openoview : "Automatski otvori pregled naselja",
    resbar : "Grafikon resursa",
    showres : "Prikaži grafikon u zasebnom prozoru",
    redbl : "Crveno (u satima)",
    yellowbl: "Žuto (u satima)",
    marketpl : "Tržnica",
    npcsum : "Sažetak za NPC",
    npcsumh : 'Prikaz u tržnici i zgradama',
    bidinc : "Povećanje ponude",
    bidinch : 'Koristi se za aukcije (Travian 4)',
    show3x : "Predviđanje kretanja kod 2x i 3x",
    show3xh : 'Pokušava predvijeti kretanje resursa kod slanja 2x i 3x (Može prikazati neispravne podatke)',
    rpandmp : "Okupljalište i Tržnica",
    incomres : "Informacije o dolazećim resursima",
    incomreso : ['Isključeno','Uključeno','S kratkim pregledom','WW mod'],
    troopsI : "Informacije o trupama",
    troopsIo : ['Isključeno','Uključeno','Skeniraj upute'],
    defRP : "Predpostavljena akcija za slanje vojske",
    showls : "Prikaži poveznice",
    showAsSN : "Koristi naziv poveznice kao drugo ime lokacije",
    showlso : ['Isključeno','Uključeno','U zasebnom prozoru'],
    savedls : "Spremljene poveznice",
    savedd : "Pohranjeni podaci",
    saveddh : 'Uključuje linkove i druge nazive naselja. Korisno ako se račun briše ili ne koristi na Vašem računalu.',
    savedelall : "Izbriši sve pohranjene podatke",
    savedelallh : 'Jeste li sigurni da želite izbrisati sve pohranjene podatke, uključujući linkove i druge nazive naselja?',
    scrlang : "Jezik skripte",
    youlang : "Tvoj jezik",
    notifi : "Obavijest",
    notification : "obavijest nakon gradnje",
    method : "Metoda",
    audiourl : "URL audio datoteke",
    audiotest : "Testiraj audio",
    colorCustomize : "Opcije boja",
    colorHint : "Pustiti prazno za predpostavljenu boju",
    color0 : "Nadogradnja dostupna",
    color1 : "Nadogradnja dostupna putem NPC-a",
    color2 : "Nadogradnja nije dostupna <br/>(Manjak resursa)",
    color3 : "Nadogradnja nije dostupna <br/>(Nedovoljna razina Skladišta/Žitnica)",
    color4 : "Nadograđeno do kraja"
  },
  bs: { fb : "hr", // Bosnian
    arena : "Mejdan",
    marketpl : "Pijaca",
    npcsumh : 'Prikaz na pijaci i zgradama',
    rpandmp : "Mjesto okupljanja i Pijaca",
    color3 : "Nadogradnja nije dostupna (Nedovoljna razina Skladišta/Silosa)"
  },
  de: { // German language, thx proll007
    // ingame messages
    ok : "Ok",
    cancel : "Abbrechen",
    close : "Schliessen",
    overview : "Ueberblick",
    svers : "Script Version",
    settings : "Einstellungen",
    notes : "Notizen",
    res90 : "Ressourcen zu % gefuellt",
    refresh : "Refresh",
    warehouse : "Warenhaus",
    resources : "Ressourcen",
    troops : "Einheiten",
    links : "Links",
    linkname : "Linkname",
    linkdel : "Link loeschen",
    name2 : "Zweiter Name",
    archive : "Archiv",
    arena : "Arena",
    addcur : "aktuelle hinzufuegen",
    del : "loeschen",
    edit : "bearbeiten",
    total : "Total",
    // settings
    auctions: "Auktionen",
    info : "Information",
    yourrace : "Deine Rasse",
    speedart : "Geschwindigkeitsartefakt",
    racelist : ['Römer','Germanen','Gallier','Natur','Nataren','Ägypter','Hunnen','detect'],
    onallp : "Alle Seiten",
    buildand : "Zeige den Countdown fuer Gebaeude und Einheiten",
    buildandh : 'In der Liste der Doerfer',
    sendres : "Zeige &laquo;sende Ressourcen/Truppen&raquo; Icons",
    sendmess : "Zeige &laquo;sende Nachricht&raquo; Icons",
    analyzer : "World-Analyzer",
    bigicon : "Zeige Versammlungsplatz Icon",
    opennote : "Oeffne Notizen automatisch",
    resbar : "Ressourcenleiste",
    showres : "Zeige Ressourcenleiste im Fenster",
    redbl : "Rot (in Stunden)",
    yellowbl: "Gelb (in Stunden)",
    marketpl : "Marktplatz",
    rpandmp : "Versammlungsplatz und Marktplatz",
    incomres : "eingehende Ressourceninfo",
    incomreso : ['aus','an','mit Summe','WW mode'],
    showls : "Zeige Links",
    showlso : ['aus','an','im Fenster'],
    savedls : "Gespeicherte Links",
    scrlang : "Scriptsprache",
    youlang : "Deine Sprache",

    // add by Cyrusx
    none : 'Nichts',
    hunger : "Hunger",
    duration : "Dauer",
    deficit : "Mangel",

    troopsI : "Information über Truppen",
    troopsIo : ['aus','an','scan Hilfe'],
    notification : "Benachrichtigung wenn Bau komplett",
    method : "Methode",
    audiourl : "URL der Audiodatei",
    audiotest : "Audiotest",
    auto : "auto",

    builtin : "Eingebaute Tools",
    builtinh : 'zur Vereinheitlichung der Produktion: Rot - meist benötigte Ressource, Grün - am wenigsten benötigte Ressource',
    normalize : 'Vereinheitlichung der Produktion',
    normal : "Normal",
    banalyze : "Eingebaute Kampfanalyse",
    cropfind : "Eingebauter Getreidefinder",
    addvtable : "Zeige zusätzliche Dorfübersicht",
    npcsum : "NPC Übersicht",
    npcsumh : 'Im Marktplatz und Gebäuden',
    bidinc : "Gebotserhöhung",
    bidinch : 'Für Auktionen in Travian4',
    defRP : "Voreinstellung für Versammlungsplatz",
    savedd : "gespeichert",
    saveddh : 'gespeicherte Links sowie Name, falls Account gelöscht oder nicht Dein Computer',
    savedelall : "Lösche alle gespeicherten Dateien",
    savedelallh : 'Wirklich alles Löschen, inkl. Links und Name?',
    notifi : "Benachrichtigung"
  },
  pt: { // Portuguese language, thx Kendra
    //traduzido por Miguel & Sam - br7
    // mensagens no jogo
    ok : "Ok",
    cancel : "Cancelar",
    close : "Fechar",
    overview : "Resumo",
    svers : "Versão do Script",
    settings : "Definições",
    notes : "notas",
    res90 : "% de recursos para encher",
    refresh : "atualizar",
    warehouse : "Armazém",
    resources : "Recursos",
    troops : "Tropas",
    links : "Links",
    linkname : "nome do link",
    linkdel : "apagar link",
    name2 : "segundo nome",
    archive : "Arquivo",
    arena : "Praça de Torneios",
    addcur : "adicionar atual",
    del : "apagar",
    edit : "editar",
    unpin : "soltar",
    pin : "fixar",
    total : "Total",
    noplace : "Não tem mais espaço!",
    hunger : "fome",
    duration : "duração",
    deficit : "em falta",
    aclock : "Alarme\nhh:mm:ss , hh:mm , mm (a partir de agora)",
    consnegat : "O consumo na aldeia está negativo. Quantos minutos precisará de reserva?",
    bmove : "Mover Edificio",
    neighbors : "vizinhos",
    // definições
    auctions: "Leilões",
    none : "Nenhum",
    auto : "automático",
    info : "Informação",
    yourrace : "Sua raça",
    sspeed : "Servidor speed",
    sspeedh : "0 - automático, 1 (1x), 2 (2x), 3 (3x), ... etc.",
    speedart : "Velocidade do artefato",
    racelist : ['Romanos','Teutões','Gauleses','Natureza','Natares','Egípcios','Hunos','detect'],
    cranny : "Nível do cereal por celeiro (Porcentagem)",
    crannyh : 'Pré-definido com 80%, 70% para pilhagem normal ou artefato',
    builtin : "Ferramentas Internas",
    builtinh : 'Para equilibrar a produção: a cor Vermelha - recursos que mais precisam; Verde - recursos que menos precisam',
    normalize : 'Equilibrar a produção',
    normal : "normal",
    banalyze : "Analisador de Ataque",
    cropfind : "Localizador de Crop's",
    adetect : "Detectar ataques",
    adetecto : ['Desligado','Modo Congelado','Ligado'],
    adetecth : "Esta opção utiliza ações ocultas no servidor, violando as regras. Poderá levar a punição do jogo.",
    adetectt : "periodo de detectar ataques",
    buildhint : "Dicas de Construção",
    onallp : "Todas as páginas",
    buildand : "Mostrar construção em contagem regressiva e atacar",
    buildandh : 'Na lista das aldeias',
    buildands : ['Desligado','Ligado','Amplo'],
    sendres : "Mostrar &laquo;Enviar reforços/tropas&raquo; icons",
    sendmess : "Mostrar &laquo;Enviar mensagem&raquo; icons",
    analyzer : "Site de ferramenta de analise",
    bigicon : "Mostrar Ponto de encontro ícone",
    addvtable : "Mostrar tabela de aldeias",
    addvtableo : ['Desligado','Ligado','Bloqueado'],
    opennote : "Abrir notas automaticamente",
    notesize : "Tamanha da janela para notas",
    openoview : "Abrir visão detalhada das aldeias",
    resbar : "Barra de Recursos",
    showres : "Mostrar barra de recursos na janela",
    redbl : "vermelho (em horas)",
    yellowbl: "amarelo (em horas)",
    marketpl : "Mercado",
    npcsum : "Resumo para NPC",
    npcsumh : 'Apareçe nos mercado e nos edificios',
    bidinc : "Valor aumentado automaticamente no leilão",
    bidinch : 'Só disponivel para a versão Travian 4',
    show3x : "Fluxo de recursos",
    show3xh : 'Tentativa de prever o fluxo de recursos no envio de 2x e 3x (Pode mostrar dados incorretos)',
    rpandmp : "Ponto de encontro e Mercado",
    incomres : "informações de recursos recebidos",
    incomreso : ['desligado','ligado','com sumário','Modo WW'],
    troopsI : "Informações sobre as tropas",
    troopsIo : ['Desligado','Ligado','Actualizado'],
    defRP : "Ação pré-definida no envio de tropas",
    showls : "Mostrar links",
    showAsSN : "Usar links como segundo nome",
    showlso : ['desligado','ligado','na janela'],
    savedls : "Links salvos",
    savedd : "Salvar dados",
    saveddh : 'incluindo links e segundo nome. Se uma conta excluída, ou não o seu computador.',
    savedelall : "Apagar todos os dados salvos",
    savedelallh :  'Tem certeza que deseja apagar todos os dados, incluindo os links e o segundo nome?',
    scrlang : "Idioma do Script",
    youlang : "Seu idioma",
    notifi : "Notificações",
    notification : "notificação após a construção",
    method : "Método",
    audiourl : "Link do ficheiro de audio",
    audiotest : "Testar Audio",
    colorCustomize : "Opções de Cores",
    colorHint : "Deixe em branco para a cor padrão",
    color0 : "Pronto para evoluir",
    color1 : "Evoluir fazendo NPC",
    color2 : "Não é possível evoluir <br/>(Falta de recursos)",
    color3 : "Não é possível evoluir <br/>(Não tem armazem e/ou celeiro suficiente)",
    color4 : "Completamente Evoluido"
  },
  bg: { // Bulgarian language, thx Dushevadeca
    // ingame messages
    ok : "Потвърди",
    cancel : "Отмени",
    close : "Затвори",
    overview : "преглед на селата",
    svers : "версия на скрипта",
    settings : "настройки",
    notes : "бележки",
    res90 : "ресурси за %-но запълване на склада",
    refresh : "опресни",
    warehouse : "Склад",
    resources : "Ресурси",
    troops : "Войски",
    links : "Бързи отметки",
    linkname : "име на отметката",
    linkdel : "изтрий отметката",
    name2 : "допълнително име",
    archive : "Архив",
    arena : "Арена",
    addcur : "добави текущата",
    del : "изтрий",
    edit : "редакция",
    unpin : "възстанови поправката",
    pin : "поправи",
    total : "Общо",
    noplace : "Там няма място!",
    hunger : "гладуване",
    duration : "продължителност",
    deficit : "дефицит",
    aclock : "Аларма в\nhh:mm:ss , hh:mm , mm (от сега)",
    consnegat : "Консумацията на жито е негативна. От колко минути запас има нужда?",
    bmove : "Премести сградите",
    neighbors : "съседи",
    // settings
    auctions: "Търгове",
    none : "Няма",
    auto : "автоматично",
    info : "Информация",
    yourrace : "Вашето племе",
    speedart : "Скоростен артефакт",
    racelist : ['Рим','Тевтонци','Гали','Nature','Natars','Egyptians','Huns','detect'],
    cranny : "предупредително(жълто) ниво на запълване на скривалището (в проценти)",
    crannyh : 'нормално- 80, 70- за класически светове или с грабителски артефакт',
    builtin : "Вградени инструменти",
    builtinh : 'за оптимизиране на производството: червено - най-необходимите ресурси, зелено - най-малко нужни',
    normalize : 'Оптимизиране на производството',
    normal : "за ресурси",
    banalyze : "Вграден анализатор на битката",
    cropfind : "Вградена търсачка за житни села",
    adetect : "Откриване на атака",
    adetecto : ['изкл.','без замръзване','вкл.'],
    adetecth : "отправя скрити заявки към сървъра, в нарушение на правилата - МОЖЕ да доведе до наказание!",
    adetectt : "интервал за проверка за атака",
    buildhint : "Подсказки за строителство",
    onallp : "Всички страници",
    buildand : "Показвай обратно броене за сгради и атаки",
    buildandh : 'В списъка на селата',
    sendres : "Показвай иконки «изпрати ресурс/войски»",
    sendmess : "Показвай иконки «изпрати съобщение»",
    analyzer : "Анализатор на игровия свят",
    bigicon : "Показвай Сборен пункт икон",
    addvtable : "Показвай допълнителна таблица със селата",
    addvtableo : ['изкл','вкл','залепи'],
    opennote : "Автоматично отваряне на бележките",
    notesize : "Размер на прозореца с бележките",
    openoview : "Автоматично отваряне на изгледа на селата",
    resbar : "Ресурсна лента",
    showres : "Показвай ресурсната лента в прозорец",
    redbl : "червено (в часове)",
    yellowbl: "жълто (в часове)",
    marketpl : "Пазар",
    npcsum : "общо ресурси за NPC",
    npcsumh : 'на пазара и при строене',
    bidinc : "стъпково увеличение на ставките с",
    bidinch : 'за аукционите в travian4',
    show3x : "да показва ли възможно неточни данни",
    show3xh : 'ще опитва да предузнае постъплението на ресурси при 3-но и 2-но изпращане',
    rpandmp : "Сборен пункт и пазар",
    incomres : "информация за постъпленията на ресурси",
    incomreso : ['изкл','вкл','с равносметки','Чудо-режим'],
    troopsI : "Информация за войски",
    troopsIo : ['изкл','вкл','обновяване'],
    defRP : "действие по подразбиране за сб. пункт",
    showls : "Покажи отметки",
    showAsSN : "Използвай отметки като второ име",
    showlso : ['изкл','вкл','в прозорец'],
    savedls : "съхранени отметки",
    savedd : "съхранени данни",
    saveddh : 'вкл. отметките и допълнителните имена на селата. В случай, че изтриете акаунта или това не е ваш компютър.',
    savedelall : "изтриване на съхранената информация и настройки",
    savedelallh : 'Сигурни сте, че искате да изтриете данните, вкл. отметки и допълнителните имена на села?',
    scrlang : "Език на скрипта",
    youlang : "вашият език",
    notifi : "известяване",
    notification : "известяване след приключване на строеж",
    method : "метод",
    audiourl : "URL на звуков файл",
    audiotest : "изпробвай звука",
    colorCustomize : "Цветови настройки",
    colorHint : "оставете празно за цвят по подразбиране",
    color0 : "възможно надграждане",
    color1 : "надграждане с NPC-търговец",
    color2 : "невъзможно надграждане(недостатъчно ресурси)",
    color3 : "невъзможно надграждане(недостатъчен капацитет на склад/хамбар)",
    color4 : "последно ниво"
  },
  ro: { // Romanian language, thx bubulu
    // ingame messages
    ok : "Ok",
    cancel : "Anulează",
    close : "Închide",
    overview : "privire generală",
    svers : "versiune script",
    settings : "setări",
    notes : "note",
    res90 : "resurse pâna la %",
    refresh : "reîmprospatare",
    warehouse : "Hambar",
    resources : "Resurse",
    troops : "Trupe",
    links : "Link-uri",
    linkname : "nume link",
    linkdel : "șterge link",
    name2 : "al doilea nume",
    archive : "Arhivă",
    arena : "Nivel arenă",
    addcur : "adaugă curent",
    del : "Șterge",
    edit : "editează",
    unpin : "anulează fixarea",
    pin : "fixează",
    total : "Total",
    noplace : "nu este loc!",
    hunger : "foame",
    duration : "durată",
    deficit : "deficit",
    aclock : "Alarmă ceas\nhh:mm:ss , hh:mm , mm (din acest moment)",
    consnegat : "Consumul de hrană în acest sat este negativ. Pentru câte minute este nevoie de rezervă de hrană?",
    bmove : "Mută clădirile",
    neighbors : "vecini",
    // settings
    auctions: "Licitații",
    none : 'None',
    auto : "auto",
    info : "Informații",
    yourrace : "Tribul dvs.",
    sspeed : "Viteza server-ului",
    sspeedh : "0 - auto, 1 (1x), 2 (2x), 3 (3x aka speed), ... etc.",
    servertype : "Tipul serverului de Travian",
    servertypeh : "Tipuri de servere: Travian Legends, Travian Shadow Empires",
    servertypeo : ['update','Shadow Empires','Legends'],
    speedart : "Artefact de viteză",
    racelist : ['Romani','Barbari','Daci','Natura','Natari','Egipteni','Huni','detectează'],
    cranny : "Culoarea galbenă la beci (în procente)",
    crannyh : 'normal 80%, 70% pentru server clasic',
    builtin : "Unelte incluse",
    builtinh : 'pentru normalizarea producției: culoarea roșie - cea mai mare nevoie de resurse, verde - cea mai mică nevoie de resurse',
    normalize : 'Normalizarea producției',
    normal : "normal",
    banalyze : "Analizor de luptă integrat",
    cropfind : "Căutător de c15 integrat",
    adetect : "Detector de atacuri",
    adetecto : ['off','fără blocare','on'],
    adetecth : "face cereri ascunse la server, care încalcă regulile. poate duce la penalizare.",
    adetectt : "Perioada de detectare a atacurilor",
    buildhint : "Sfaturi pentru construcții (culori)",
    onallp : "Toate paginile",
    buildand : "Arată numărătoarea inversă pentru construcții și atacuri",
    buildandh : 'în lista satelor',
    buildands : ['off','on','detaliat'],
    sendres : "Arată icoana &laquo;trimite resurse/trupe&raquo;",
    sendmess : "Arată icoana &laquo;trimite mesaj&raquo;",
    analyzer : "Analizor server",
    bigicon : "Arată icoana pentru Adunare",
    addvtable : "Arată lista suplimentară cu sate",
    addvtableo : ['off','on','fix'],
    opennote : "Deschide fereastra de notițe automat",
    notesize : "Dimensiunea ferestrei de notițe",
    openoview : "Deschide fereastra cu privirea generală automat",
    resbar : "Bara de resurse",
    showres : "Afișează bara de resurse în fereastră",
    redbl : "roșu (în ore)",
    yellowbl: "galben (în ore)",
    marketpl : "Târg",
    npcsum : "Sumar pentru NPC",
    npcsumh : 'la târg și la clădiri',
    bidinc : "Mărește oferta licitațiilor cu (în arginți)",
    bidinch : 'Introdu 0 pentru a dezactiva funcția',
    show3x : "Prezice fluxul de resurse la trimiterea cu 3x și 2x",
    show3xh : 'poate afișa informații imprecise',
    rpandmp : "Adunare și Târg",
    incomres : "Informații resurse ce sosesc",
    incomreso : ['off','on','cu sumar','mod WW'],
    troopsI : "Informații despre trupe",
    troopsIo : ['off','on','scan help'],
    defRP : "Acțiune implicită la adunare",
    showls : "Arată link-uri",
    showAsSN : "Folosiți link-urile cu numele secundar",
    showlso : ['off','on','în fereastră'],
    savedls : "link-uri salvate",
    savedd : "Date salvate",
    saveddh : 'inclusiv link-urile și numele secundare ale satelor. If an Account deleted, or not your computer.',
    savedelall : "Șterge toate datele",
    savedelallh : 'Ești sigur că vrei să ștergi toate datele, inclusiv link-urile și numele secundare ale satelor?',
    scrlang : "Limbă script",
    youlang : "Limba browser-ului",
    notifi : "Notificări",
    notification : "notificare după construcție",
    method : "Metoda",
    audiourl : "URL of audio file",
    audiotest : "Test audio",
    colorCustomize : "Opțiuni culori",
    colorHint : "lasă gol pentru culorile implicite",
    color0 : "Upgrade disponibil",
    color1 : "Upgrade via NPC",
    color2 : "Upgrade-ul nu este posibil <br/>(nu sunt suficiente resurse)",
    color3 : "Upgrade-ul nu este posibil <br/>(grânarele / hambarele nu au capacitatea suficientă)",
    color4 : "Nivel final"
  },
  sr: { // Serbian language, thx jokusaet
    // ingame messages
    ok : "Ok",
    cancel : "Откажи",
    close : "Затвори",
    overview : "Преглед",
    svers : "Верзија скрипте",
    settings : "Подешавања",
    notes : "Белешке",
    res90 : "Ресурси до % попуњености",
    refresh : "Освежи",
    warehouse : "Складиште",
    resources : "Ресурси",
    troops : "Јединице",
    links : "Линкови",
    linkname : "Име линка",
    linkdel : "Обриши линк",
    name2 : "Друго име",
    archive : "Архива",
    arena : "Витешка арена",
    addcur : "Додај тренутну страну",
    del : "Обриши",
    edit : "Измени",
    total : "Укупно",
    noplace : "Нема довољно места!",
    hunger : "Глад",
    duration : "Трајање",
    deficit : "Дефицит",
    // settings
    auctions: "Аукције",
    none : "Ништа",
    auto : "Ауто",
    info : "Инфо",
    yourrace : "Твоја раса",
    speedart : "Артефакт брзих",
    racelist : ['Римљани','Тевтонци','Гали','Nature','Natars','Egyptians','Huns','detect'],
    cranny : "Жути ниво силоса (проценат)",
    crannyh : 'нормално 80, 70 ѕа класично и артефакт',
    builtin : "Уграђени алати",
    builtinh : 'за нормализацију производње: црвена боја - најпотребнији ресурси, зелена - мање потребни ресурси',
    normalize : 'нормализација производње',
    normal : "нормално",
    banalyze : "уграђен анализатор битке",
    cropfind : "уграђени претраживач житница",
    onallp : "све стране",
    buildand : "покажи одбројавање грађевина и напад",
    buildandh : 'У листи села',
    sendres : "Прикажи &laquo;пошаљи ресурсе/јединице&raquo; иконе",
    sendmess : "Прикажи &laquo;пошаљи поруку&raquo; иконе",
    analyzer : "World analyzer",
    bigicon : "Прикажи Место окупљања иконе",
    addvtable : "Прикажи додатну табелу са листом села",
    opennote : "Аутоматски отвори белешке",
    resbar : "Табела са ресурсима",
    showres : "Прикажи табелу са ресурсима у прозору",
    redbl : "црвено (у сатима)",
    yellowbl: "жуто (у сатима)",
    marketpl : "Пијаца",
    npcsum : "сума за НПЦ",
    npcsumh : 'у пијаци и зградама',
    bidinc : "повећање понуде на берзи",
    bidinch : 'за аукције на Т4',
    rpandmp : "Место окупљања и Пијаца",
    incomres : "инфо о долазећим ресурсима",
    incomreso : ['искључен','укључен','са сумом','WW мод'],
    troopsI : "Информације о јединицама",
    troopsIo : ['искључено','укључено','помоћ при скенирању'],
    defRP : "подразумевана акција у месту окупљања",
    showls : "Прикажи линкове",
    showlso : ['искључено','укључено','у прозору'],
    savedls : "сачувани линкови",
    savedd : "сачувани подаци",
    saveddh : 'укључујући линкове и друго име. Уколико је налог обрисан, или није твој компјутер.',
    savedelall : "обриши све сачуване податке",
    savedelallh : 'Да ли си сигуран да желиш да обришеш све сачуване податке, укључујући и линкове и друго име?',
    scrlang : "Језик скрите",
    youlang : "твој језик",
    notifi : "нотификација",
    notification : "нотификација за изградњу",
    method : "метода",
    audiourl : "УРЛ аудио фајла",
    audiotest : "тестирај аудио",
    // thx Stevan
    neighbors : "суседи",
    colorCustomize : "Опције боја",
    colorHint : "остави празно за предефинисане боје",
    color0 : "надоградња могућа",
    color1 : "надоградња кроз НПЦ",
    color2 : "надоградња није могућа<br/>(нема довољно ресурса)",
    color3 : "надоградња није могућа<br/>(недовољан капацитет силоса/складишта)",
    color4 : "последњи ниво"
  },
  pl: { // Polish translation, thx aren
    // ingame messages
    ok : "Ok",
    cancel : "Anuluj",
    close : "Zamknij",
    overview : "Przegląd",
    svers : "wersja skryptu",
    settings : "ustawienia",
    notes : "notatki",
    res90 : "środków na % napełniania",
    refresh : "odśwież",
    warehouse : "Magazyn",
    resources : "Surowce",
    troops : "Jednostki",
    links : "Linki",
    linkname : "nazwa linka",
    linkdel : "usuń link",
    name2 : "druga nazwa",
    archive : "Archiwum",
    arena : "Plac Turniejowy",
    addcur : "dodaj bieżący",
    del : "usuń",
    edit : "edytuj",
    total : "Razem",
    noplace : "Nie ma miejsca!",
    hunger : "głód",
    duration : "czas trwania",
    deficit : "deficyt",
    // settings
    auctions: "Aukcje",
    none : "Brak",
    auto : "auto",
    info : "Informacja",
    yourrace : "Twoja rasa",
    speedart : "Prędkość artefaktu",
    racelist : ['Rzymianie','Germanie','Galowie','Dzikie zwierzęta','Natarzy','Egipcjanie','Hunowie','detect'],
    cranny : "żółty poziom kryjówki (procent)",
    crannyh : 'normalny 80, 70 do grabieży na klasycznym lub artefakcie',
    builtin : "Wbudowane narzędzia",
    builtinh : 'dla normalizacji produkcji: kolor czerwony - najwięcej środków potrzeba, zielony - potrzeba mniej zasobów',
    normalize : 'normalizacja produkcji',
    normal : "normalny",
    banalyze : "Wbudowany analizator bitwy",
    cropfind : "Wbudowany poszukiwacz cropów",
    onallp : "Wszystkie strony",
    buildand : "Pokaz odliczanie budynku i ataku",
    buildandh : 'Na liście osad',
    sendres : "Pokaz &laquo;wyślij surowce/jednostki&raquo; ikony",
    sendmess : "Pokaz &laquo;wyślij wiadomość&raquo; ikony",
    analyzer : "World analyzer",
    bigicon : "Pokaz Miejsce zbiórki ikona",
    addvtable : "Pokaz dodatkowa tablice osad",
    opennote : "Automatycznie otwórz notatnik",
    resbar : "Tabela surowców",
    showres : "Pokaz tabele surowców w oknie",
    redbl : "czerwony (w godzinach)",
    yellowbl: "żółty (w godzinach)",
    marketpl : "Rynek",
    npcsum : "podsumowanie dla NPC",
    npcsumh : 'na rynku i budynkach',
    bidinc : "przebicie oferty",
    bidinch : 'na aukcji travian4',
    rpandmp : "Miejsce zbiórki i Rynek",
    incomres : "informacja o przychodzących surowcach",
    incomreso : ['off','on','z podsumowaniem','WW mode'],
    troopsI : "Informacja o jednostkach",
    troopsIo : ['off','on','scan help'],
    defRP : "domyślna akcja dla Miejsca zbiórki",
    showls : "Pokaz linki",
    showlso : ['off','on','w oknie'],
    savedls : "zapisane linki",
    savedd : "zapisane dane",
    saveddh : 'w tym Linki i Druga nazwa. Jeśli konto usunięte, albo nie twój komputer.',
    savedelall : "usunąć wszystkie zapisane dane",
    savedelallh : 'Czy na pewno chcesz usunąć wszystkie dane, w tym linki i druga nazwe?',
    scrlang : "Język skryptu",
    youlang : "twój język",
    notifi : "powiadomienie",
    notification : "powiadomienia po zakończeniu budowy",
    method : "metoda",
    audiourl : "Adres URL pliku audio",
    audiotest : "test audio"
  },
  sv:{ // Swedish translation, thx Dragon from the future
    // Meddelande,
    ok : "Ok",
    cansel : "Avbryt",
    close : "Stäng",
    Overview : "överblick",
    svers : "script version",
    setting : "inställningar",
    notes : "Anteckningar",
    res90 : "Resurser över 90 %",
    refresh : "Uppdatera",
    warehouse : "Magasin",
    resources : "Råvaror",
    troops : "Soldater",
    links : "Länkar",
    linkname : "Länknamn",
    linkdel : "Radera länk",
    name2 : "Andra namn",
    archive : "Arkiv",
    arena : "Torneplats",
    addcur : "Lägg till nuvarande",
    del : "radera",
    edit : "ändra",
    total : "Totalt",
    noplace : "Det finns ingen plats",
    hunger : "Svält",
    duration : "Varaktighet",
    deficit : "Underskott",
    // inställningar
    auctions: "Auktion(er)",
    none : "Inga",
    auto : "auto",
    info : "Information",
    yourrace : "Din stam",
    speedart : "Titanskor",
    racelist : ['Romare','Germaner','Galler','Natur','Natarer','Egyptierna','Hunnerna','detect'],
    cranny : "Gul nivå på grotta (procent)",
    crannyh : "Normal 80, 70 för klssisk eller artefakt-plundrare",
    builtin : "Inbyggda hjälpmedel",
    builtinh : "För att återställa produktionen: röd färg - Behövs mest resurser, green - behövs mindre resurser",
    normalize : "Återställ produktionen",
    normal : "normal",
    banalyze : "inbyggd analysator för slag",
    cropfins : "inbyggd veteby-finnare",
    onallp : "Alla sidor",
    buildand : "Visa byggnings och attack nedräkning",
    buildandh : "I bylistan",
    sendres : "Visa &laquo;sänd råvaror/trupper&raquo; ikoner",
    sendmess : "Visa Skicka meddelande ikoner",
    analyzer : "Världsanalysator",
    bigicon : "Visa samlingsplats ikoner",
    addvtable : "Visa extra bylista",
    opennote : "Öppnar automatisk anteckningar",
    resbar : "Råvaror-fält",
    showres : "Visa råvaror-fältet i ett eget fönster",
    redbl : "röd (i timmar)",
    yellowbl : "yellow (i timmar)",
    marketpl : "Marknadsplats",
    npcsum : "summering för NPC",
    npcsumh : "I marknadsplats och och byggnader",
    incomres : "ikommande råvaro-info",
    incomreso : ['av','på','med sammanfattning','Världsunder'],
    troppsl : "Information om soldaterna",
    troopslo : ['av','på','i fönster'],
    defRP : "Förvald attacktyp på samlingsplats",
    showls : "Visa länkar",
    showlso : ['av','på','i fönster'],
    savedls : "sparade länkar",
    savedd : "sparad data",
    saveddh : 'Inkluderar länkar och andra-namn. Är ett konto raderat, eller inte din dator.',
    savedelall : "Radera all sparad data",
    savedelallh : 'Är du säker på att du vill radera all data, länkar och andra namnpå byar?',
    scrlang : "Script språk",
    youlang : "ditt språk",
    notifi : "notifikation",
    notification : "Notifikation efter byggande",
    method : "metod",
    audiourl : "URL för ljudfil",
    audiotest : "ljudtest"
  },
  it: { // Italian translation , Dragonflame
    // ingame messages
    ok : "Ok",
    cancel : "Cancella",
    close : "Chiudi",
    overview : "Mostra",
    svers : "Versione dello script",
    settings : "Configurazione",
    notes : "Blocco note",
    res90 : "Risorse a % della capacità",
    refresh : "Aggiorna",
    warehouse : "Magazzino",
    resources : "Risorse",
    troops : "Truppe",
    links : "Links",
    linkname : "Nome del link",
    linkdel : "Cancella link",
    name2 : "Secondo Nome",
    archive : "Archivio",
    arena : "Arena",
    addcur : "Aggiungi corrente",
    del : "Cancella",
    edit : "Modifica",
    total : "Totale",
    noplace : "Non c'è posto!",
    hunger : "Fame",
    duration : "Durata",
    deficit : "Deficit",
    // settings
    auctions: "Aste",
    none : 'Nessuno',
    auto : "auto",
    info : "Informazioni",
    yourrace : "La tua Tribù:",
    speedart : "Artefatto velocità",
    racelist : ['Romani','Teutoni','Galli','Belve','Nataren','Egiziani','Unni','detect'],
    cranny : "Livello giallo della capacità del deposito segreto (%)",
    crannyh : 'Normalmente 80; Per il server classico o per artefatto del Ladro 70;',
    builtin : "Strumenti Integrati",
    builtinh : 'Per la produzione ottimizzata: Rosso = Servono più risorse; Verde = servono meno risorse;',
    normalize : 'Produzione ottimizzata',
    normal : "Risorse",
    banalyze : "Analizzatore di Battaglia integrato",
    cropfind : "Trova Canarini integrato",
    adetect : "Rilevatore d'attacchi",
    adetecto : ['Spento','Senza Blocco','Acceso'],
    adetecth : "Fa richieste al server di nascosto, violando le regole. Punibile.",
    adetectt : "Periodo di rilevamento attacco",
    onallp : "Su tutte le pagine",
    buildand : "Mostra il conto alla rovescia per gli edifici e gli attacchi",
    buildandh : 'Nella lista dei villaggi',
    sendres : "Mostra le icone «invia risorse / truppe»",
    sendmess : "Mostra icone «invia messaggio»",
    analyzer : "World analyzer",
    bigicon : "Mostra icone di Base Militare",
    addvtable : "Mostra una tabella villaggi aggiuntiva ",
    opennote : "Aprire il blocco note automaticamente",
    resbar : "Tabella delle Risorse",
    showres : "Mostra la tabella delle risorse in una finestra",
    redbl : "Rosso (in ore)",
    yellowbl: "Giallo (in ore)",
    marketpl : "Mercato",
    npcsum : "Riepilogo per NPC",
    npcsumh : 'Nel mercato e negli edifici',
    bidinc : "Incremento dell'offerta",
    bidinch : 'Per le aste travian4',
    rpandmp : "Base Militare e Mercato",
    incomres : "Info sulle risorse in arrivo",
    incomreso : ['No','Si','Con risultati','Modalità Meraviglia'],
    troopsI : "Informazioni sulle truppe",
    troopsIo : ['Spento','Acceso','Scansione di aiuto'],
    defRP : "Azione predefinita per «Invia truppe»",
    showls : "Mostra link",
    showlso : ['No','Si','In una finestra'],
    savedls : "Salva link",
    savedd : "Salva Dati",
    saveddh : 'Incluso Links e Secondo nome. Se un Account viene cancellato, o non è il tuo computer.',
    savedelall : "Cancella tutti i dati",
    savedelallh : 'Sei sicuro di voler cancellare tutti dati, incluso i links ed i Secondi nomi?',
    scrlang : "Scelta della lingua",
    youlang : "Lingua del browser",
    notifi : "Notifiche",
    notification : "Notifica dopo il completamento della construzione",
    method : "Metodo",
    audiourl : "URL del file audio",
    audiotest : "test audio"
  },
  es: {// Spanish translation. neonsp
    // ingame messages
    ok : "Ok",
    cancel : "Cancelar",
    close : "Cerrar",
    overview : "Vista previa aldeas",
    svers : "Versión Script",
    settings : "Ajustes",
    notes : "notass",
    res90 : "recursos hasta % llenado",
    refresh : "actualizar",
    warehouse : "Almacen",
    resources : "Recursos",
    troops : "Tropas",
    links : "Enlaces",
    linkname : "Nombre enlace",
    linkdel : "Borrar enlace",
    name2 : "Segundo nombre",
    archive : "Archivo",
    arena : "Plaza de torneos",
    addcur : "añadir actual",
    del : "borrar",
    edit : "editar",
    unpin : "unfix",
    pin : "fix",
    total : "Total",
    noplace : "No hay sitio!",
    hunger : "Hambre",
    duration : "duración",
    deficit : "Deficit",
    aclock : "Alarma Reloj\nhh:mm:ss , hh:mm , mm (desde ahora)",
    consnegat : "El consumo en esta aldea es negativoive. Cuantos minutos necesita de reserva?",
    bmove : "Mover edificios",
    neighbors : "vecinos",
    // settings
    auctions: "Subasta",
    none : "Ninguno",
    auto : "auto",
    info : "Información",
    yourrace : "Raza",
    speedart : "Artefacto de velocidad",
    racelist : ['Romanos','Germanos','Galos','Nature','Natars','Egyptians','Huns','detect'],
    cranny : "Nivel amarillo para el granero ( porcentaje )",
    crannyh : 'normal 80, 70 para clásico o artefacto de saqueo',
    builtin : "Herramientas adjuntas",
    builtinh : 'Para normalizar la producción: Rojo - Más recursos necesarios, Verde - menos recursos necesarios',
    normalize : 'Normalizado de la producción',
    normal : "normal",
    banalyze : "Analizador de batallas",
    cropfind : "Buscador de cerealeras",
    adetect : "Detectar ataques",
    adetecto : ['No','Sin pausa','Si'],
    adetecth : "realiza peticiones en segundo plano al servidor, violando las normas. Puedes ser sancionado por ello.",
    adetectt : "Frecuencia de detección de ataques",
    buildhint : "Consejos de construcción",
    onallp : "Todas las páginas",
    buildand : "Mostrar cuenta atrás de construcciones y ataques",
    buildandh : 'En la lista de aldeas',
    buildands : ['Si','No','Ancho'],
    sendres : "Mostrar iconos de &laquo;enviar recursos/tropas&raquo; ",
    sendmess : "Mostrar iconos de &laquo;enviar mensaje&raquo; ",
    analyzer : "Analizador del Mapa",
    bigicon : "Mostrar Plaza de reuniones icono",
    addvtable : "Mostrar tabla adicional de aldea",
    addvtableo : ['Si','No','Fijado'],
    opennote : "Abrir automáticamente las notas",
    notesize : "Tamaño de la ventana de notas",
    openoview : "Abrir automáticamente visión general de aldeas",
    resbar : "Barra de recursos",
    showres : "Mostrar recursos en la ventana",
    redbl : "Rojo (en horas)",
    yellowbl: "Amarillo (en horas)",
    marketpl : "Mercado",
    npcsum : "Resumen para NPC",
    npcsumh : 'en mercado y edificios',
    bidinc : "Aumento de puja",
    bidinch : 'Para subastas de Travian4',
    show3x : "Intentar predecir el flujo de recrusos con doble y triple envio",
    show3xh : 'Puede ser incorrecto',
    rpandmp : "Plaza de reuniones y mercado",
    incomres : "Información de recursos entrantes",
    incomreso : ['Si','No','Con resumen','Modo maravilla'],
    troopsI : "Information about the troops",
    troopsIo : ['Si','No','Ayuda de escaneo'],
    defRP : "Acción por defecto en plaza reuniones",
    showls : "Mostrar enlaces",
    showAsSN : "Usar enlaces con el segundo nombre",
    showlso : ['Si','No','en ventana'],
    savedls : "Enlaces guardados",
    savedd : "Datos guardados",
    saveddh : 'Incluyendo enlaces y segundo nombre. If an Account deleted, or not your computer.',
    savedelall : "Borrar todos los datos almacenados",
    savedelallh : '¿Realmente deseas borrar todo los datos, incluyendo los enlaces y segundos nombres?',
    scrlang : "Idioma del Script",
    youlang : "Tu idioma",
    notifi : "notificación",
    notification : "Notificación al finalizar construción",
    method : "Método",
    audiourl : "URL del archivo de audio",
    audiotest : "prueba del audio",
    colorCustomize : "Opciones de colores",
    colorHint : "dejar en blanco para el color por defecto",
    color0 : "mejora disponible",
    color1 : "mejorar mediante NPC",
    color2 : "Mejora imposible <br/>(Recursos insuficientes)",
    color3 : "Mejora imposible <br/>(Capacidad de granero o almacenes insuficiente)",
    color4 : "Máximo nivel"
  },
  zh: {// Chinese (Taiwan) (tw and cn and hk) translation. atg008782
    // 遊戲訊息(ingame messages)
    ok : "確定",
    cancel : "取消",
    close : "關閉",
    overview : "村莊預覽",
    svers : "腳本版本",
    settings : "設定",
    notes : "筆記",
    res90 : "資源 % 上限",
    refresh : "刷新",
    warehouse : "倉庫",
    resources : "資源",
    troops : "部隊",
    links : "連結",
    linkname : "名稱連結",
    linkdel : "刪除連結",
    name2 : "第二名稱",
    archive : "存檔",
    arena : "競技場",
    addcur : "添加",
    del : "刪除",
    edit : "編輯",
    unpin : "未修復",
    pin : "修復",
    total : "總數",
    noplace : "沒有空位!",
    hunger : "飢餓",
    duration : "時間",
    deficit : "紅字",
    aclock : "警報時間\nhh:mm:ss , hh:mm , mm (從現在起)",
    consnegat : "在這個村莊的儲存量是負的. 剩下儲存量多少分鐘?",
    bmove : "移動建築",
    // 設定(settings)
    auctions: "拍賣",
    none : "無",
    auto : "自動",
    info : "訊息",
    yourrace : "你的種族",
    speedart : "伺服器倍速",
    racelist : ['羅馬','條頓','高盧','Nature','Natars','埃及人','匈奴','detect'],
    cranny : "黃色警戒線 (百分比)",
    crannyh : '一般 80, 70 經典或藝術品加成',
    builtin : "置入工具",
    builtinh : '產量欄顯示：紅色-為缺乏的資源，綠色-為不缺乏的資源',
    normalize : '標準生產',
    normal : "一般",
    banalyze : "置入戰鬥分析器",
    cropfind : "置入搜田器",
    adetect : "攻擊檢測",
    adetecto : ['關閉','w/o停止','開啟'],
    adetecth : "使用隱藏功能違反遊戲規則可能會導致懲罰.",
    adetectt : "檢測攻擊時間",
    buildhint : "建設提示",
    onallp : "全部頁面",
    buildand : "顯示建設和攻擊倒數計時",
    buildandh : '村內列表',
    sendres : "顯示 資源/部隊 傳輸圖示",
    sendmess : "顯示傳送訊息圖示 ",
    analyzer : "世界分析",
    bigicon : "顯示集結點示",
    addvtable : "額外顯示村莊列表",
    addvtableo : ['關閉','開啟','固定'],
    opennote : "自動開啟筆記",
    notesize : "筆記視窗尺寸",
    openoview : "自動開啟村莊預覽",
    resbar : "資源欄",
    showres : "顯示資源欄視窗",
    redbl : "紅(每小時)",
    yellowbl: "黃(每小時)",
    marketpl : "市場",
    npcsum : "電腦商人交易(NPC)",
    npcsumh : '在市場與建築',
    bidinc : "拍賣加價",
    bidinch : ' travian 4 拍賣',
    show3x : "可能顯示不正確的數據",
    show3xh : '嘗試預測在 3倍 和 2倍 的資源傳輸',
    rpandmp : "集結點 與 市場",
    incomres : "資源傳輸信息",
    incomreso : ['關閉','開啟','電腦交易','奇觀模式'],
    troopsI : "部隊訊息",
    troopsIo : ['關閉','開啟','掃描幫助'],
    defRP : "默認集結點",
    showls : "顯示鏈接",
    showAsSN : "使用第二名稱",
    showlso : ['關閉','開啟','視窗顯示'],
    savedls : "儲存鏈接",
    savedd : "儲存數據",
    saveddh : '電腦不是你的如果要刪除,刪除項目會包含鏈接和第二名稱',
    savedelall : "全部儲存數據刪除",
    savedelallh : '你確定要刪除所有數據，包括鏈接和第二名稱嗎？',
    scrlang : "腳本語言",
    youlang : "你的語言",
    notifi : "通報",
    notification : "建設完成通報",
    method : "方式",
    audiourl : "音樂網址",
    audiotest : "播放音樂"
  },
  tr: { // Turkish language. xpugur
    // ingame messages
    ok : "Tamam",
    cancel : "iptal",
    close : "Kapat",
    overview : "Köylerin genel görünümü",
    svers : "kod versiyonu",
    settings : "ayarlar",
    notes : "notlar",
    res90 : "kaynaklar doluyor % ",
    refresh : "yenile",
    warehouse : "Depo",
    resources : "Kaynaklar",
    troops : "Askerler",
    links : "Bağlantılar",
    linkname : "bağlantı adı",
    linkdel : "bağlantıyı sil",
    name2 : "ikinci ad",
    archive : "Arşiv",
    arena : "Turnuva alanı",
    addcur : "mevcutu ekle",
    del : "sil",
    edit : "ayarla",
    unpin : "düzeltme",
    pin : "düzelt",
    total : "Toplam",
    noplace : "Yer yok!",
    hunger : "açlık",
    duration : "süre",
    deficit : "eksiklik",
    aclock : "Alarm saati\nhh:mm:ss , hh:mm , mm (şuandan itibaren)",
    consnegat : "Bu köyde tüketim eksilerde. Kaç dakika gerekiyor rezervlerin dolması için?",
    bmove : "Binaları taşı",
    // settings
    auctions: "Açık Artırma",
    none : "Yok",
    auto : "otomatik",
    info : "Bilgi",
    yourrace : "Irkın",
    speedart : "Hız eseri",
    racelist : ['Romanlılar','Cermenler','Galyalılar','Nature','Natarlar','Mısırlılar','Hunlar','detect'],
    cranny : "sığınak sarı seviyesi (yüzde)",
    crannyh : 'normal 80, klasik veya eser yağması için 70 ',
    builtin : "Entegre araçlar",
    builtinh : 'Üretimi normalleştirmek için: kırmızı renk - en gerekli kaynak, yeşil - en az gerekli kaynak',
    normalize : 'Üretimi normalleştirmek için',
    normal : "normal",
    banalyze : "Dahili savaş analizcisi",
    cropfind : "Dahili tarla bulucu",
    adetect : "Saldırıları algıla",
    adetecto : ['kapa','w/o dondur','aç'],
    adetecth : "Server a gizli istekler gönderir, kural ihlalidir. Ceza gelebilir.",
    adetectt : "saldırı algılama zaman aralıkları",
    buildhint : "inşaat ipuçları",
    onallp : "Tüm sayfalar",
    buildand : "inşaat gerisayımını ve saldırıları göster",
    buildandh : 'Köy listelerinde',
    sendres : "işaretleri göster: ?send resource/troops? ",
    sendmess : "işaretleri göster: ?send message? ",
    analyzer : "Dünya analizcisi",
    bigicon : "Git-gel noktası simgesi göster",
    addvtable : "Ek köy tablosunu göster",
    addvtableo : ['kapa','aç','sabitle'],
    opennote : "Otomatik olarak notları aç",
    notesize : "Notlar için pencere boyutu",
    openoview : "Otomatik olarak köylerin genel görüşünü aç",
    resbar : "Kaynaklar çubuğu",
    showres : "Kaynaklar çubuğunu pencerede göster",
    redbl : "kırmızı (saat olarak)",
    yellowbl: "sarı (saat olarak)",
    marketpl : "Market",
    npcsum : "NPC için özet",
    npcsumh : 'binalarda ve markette',
    bidinc : "teklif arttır",
    bidinch : 'travian4 açık-arttırmaları için',
    show3x : "yanlış veri gösterebilir",
    show3xh : '3x ve 2x ile gönderilen kaynak akışını tahmin etmeye çalış',
    rpandmp : "Marketteki git-gel noktası",
    incomres : "gelen kaynak bilgisi",
    incomreso : ['kapa','aç','özetle','WW modu'],
    troopsI : "Askerler hakkında bilgi",
    troopsIo : ['kapa','aç','yardım ara'],
    defRP : "git-gel noktası için standart hareket",
    showls : "Bağlantıalrı göster",
    showAsSN : "Bağlantıları ikinci isim olarak kullan",
    showlso : ['kapa','aç','pencerede'],
    savedls : "kaydedilmiş bağlantılar",
    savedd : "kaydedilmiş veriler",
    saveddh : 'bağlantılar ve ikinci ismi içeren. Hesap silindiyse, yada kendi bilgisayarınız değilse.',
    savedelall : "kaydedilmiş tüm verileri sil",
    savedelallh : 'ikinci isim ve bağlantıları içeren, tüm verileri silmekte emin misiniz?',
    scrlang : "Kod dili",
    youlang : "Kendi diliniz",
    notifi : "bilgilendirmeler",
    notification : "inşaattan sonra bilgilendirmeler",
    method : "method",
    audiourl : "ses dosyasının URL si",
    audiotest : "test sesi"
  },
  vi: { // VietNamese translation by Nguyễn Duy Thanh
    // ingame messages
    ok : "Đồng ý",
    cancel : "Huỷ bỏ",
    close : "Đóng",
    overview : "tổng quan làng",
    svers : "Phiên bản scripts(translator thanhgola):",
    settings : "Cài đặt",
    notes : "ghi chú",
    res90 : "Tài nguyên cần để đầy %",
    refresh : "làm tươi",
    warehouse : "nhà kho",
    resources : "Tài nguyên",
    troops : "Lính",
    links : "Liên kết",
    linkname : "tên liên kết",
    linkdel : "xoá liên kết",
    name2 : "tên phụ",
    archive : "Lưu trữ",
    arena : "Võ đài",
    addcur : "thêm liên kết hiện tại",
    del : "xoá",
    edit : "sửa",
    unpin : "gỡ",
    pin : "sửa",
    total : "Tổng",
    noplace : "Không có chỗ!",
    hunger : "đói",
    duration : "Thời gian",
    deficit : "Thâm hụt",
    aclock : "Đồng hồ báo\nhh:mm:ss , hh:mm , mm ( tính từ bây giờ)",
    consnegat : "Mức tiêu thụ âm. Cần bao nhiêu phút để dự trữ?",
    bmove : "Dời công trình",
    // settings
    auctions: "Đấu giá",
    none : "Không",
    auto : "tự động",
    info : "Thông tin",
    yourrace : "Chủng tộc của bạn",
    speedart : "Cỗ xe của Helios",
    racelist : ['Romans','Teutons','Gauls','Nature','Natars','Egyptians','Huns','detect'],
    cranny : "Báo màu vàng khi ống tài nguyên đạt (%)",
    crannyh : 'thông thường là 80, 70 cho làng bình thường hoặc làng có Bình rượu của Dionysus',
    builtin : "Công cụ công trình",
    builtinh : 'Chuẩn hoá sản lượng tài nguyên: màu đỏ -loại tài nguyên cần nhất, màu xanh - loại tài nguyên ít cần',
    normalize : 'Chuẩn hoá sản lượng tài nguyên',
    normal : "chuẩn",
    banalyze : "Chức năng - phân tích trận chiến",
    cropfind : "Chức năng - tìm làng nhiều ruộng lúa",
    adetect : "Phát hiện tấn công",
    adetecto : ['tắt','w/o mặc định','mở'],
    adetecth : "ẩn các hành vi có thể dẫn đến hình phát",
    adetectt : "Thời gian phát hiện tấn công",
    buildhint : "Mẹo xây dựng",
    onallp : "Tất cả trang",
    buildand : "Hiển thị thời gian xây dựng và tấn công",
    buildandh : 'Trong danh sách làng',
    sendres : "Hiện biểu tượng «Gửi tài nguyên/Gửi lính»",
    sendmess : "Hiện biểu tượng <<gửi>>",
    analyzer : "Phân tích thế giới",
    bigicon : "Hiện biểu tượng Binh trường",
    addvtable : "Hiển thị danh sách làng bổ sung",
    addvtableo : ['tắt','mở','dính'],
    opennote : "Tự động mở ghi chú",
    notesize : "Kích thước của sổ ghi chú",
    openoview : "Tự động mở tổng quát làng",
    resbar : "Thanh tài nguyên",
    showres : "Hiện thanh tài nguyên trên cửa sổ",
    redbl : "Đỏ (giờ)",
    yellowbl: "Vàng (giờ)",
    marketpl : "Khu chợ",
    npcsum : "Tóm tắt cho NPC",
    npcsumh : 'chợ và công trình',
    bidinc : "Tăng đấu giá",
    bidinch : 'đấu giá của travian4',
    show3x : "Có thể hiện thị dữ lệu không chính xác",
    show3xh : 'cố gắn dự đoán các luồn tài nguyên sever 2x và 3x đang gửi',
    rpandmp : "Binh trường và chợ",
    incomres : "Thông tin tài nguyên đang đến",
    incomreso : ['tắt','mở','với tóm tắt','chế độ WW'],
    troopsI : "Thông tin về quân đội",
    troopsIo : ['tắt','mở','tìm trợ giúp'],
    defRP : "Hành động mặt định khi gửi lính",
    showls : "Hiện liên kết",
    showAsSN : "Sử dụng liên kết như tên phụ",
    showlso : ['tắt','mở','trong cửa sổ'],
    savedls : "Lưu liên kết",
    savedd : "Liên kết đã lưu",
    saveddh : 'gồm liên kết và liên kết phụ. Nếu tài khoảng xoá hoặc đây không phải máy tính của bạn.',
    savedelall : "xoá tất cả dữ liệu đã lưu",
    savedelallh : 'bạn có chắc muốn xoá hết dữ liệu, bao gồm cả liên kết và tên phụ cuả nó?',
    scrlang : "Ngôn ngữ Script",
    youlang : "Ngôn ngữ của bạn",
    notifi : "Thông báo",
    notification : "thông báo sau khi xây dựng xong",
    method : "Phương pháp",
    audiourl : "URL của tệp nhạc",
    audiotest : "Thử nhạc",
    neighbors : "Tìm kiếm",
    colorCustomize : "Cài đặt màu sắc",
    colorHint : "Để trống để cho màu mặc định",
    color0 : " Sẵn sàn nân cấp ",
    color1 : "Nân cấp thông qua NPC",
    color2 : "Không thể nân cấp<br>(do không đủ tài nguyên)",
    color3 : "không thể nân cấp<br>(do nhà kho/ kho lúa không đủ sức chứa)",
    color4 : "Hoàn thành nân cấp"
  },
  el: {// Greek translation by Tasos el malo
    // ingame messages
    ok : "εντάξει",
    cancel : "ακύρωση",
    close : "κλείσε",
    overview : "επισκόπηση χωριών",
    svers : "έκδοση script",
    settings : "ρυθμίσεις",
    notes : "σημειώσεις",
    res90 : "πόροι για την πλήρωση %",
    refresh : "ανανέωση",
    warehouse : "αποθήκη",
    resources : "πόροι",
    troops : "στρατεύματα",
    links : "σύνδεσμοι",
    linkname : "όνομα συνδέσμου",
    linkdel : "διαγραφή συνδέσμου",
    name2 : "2ο όνομα",
    archive : "αρχείο",
    arena : "πλατεία αθλημάτων",
    addcur : "προσθήκη τρέχουσας",
    del : "διαγραφή",
    edit : "επεξεργασία",
    unpin : "unfix",
    pin : "fix",
    total : "σύνολο",
    noplace : "δεν υπάρχει χώρος!",
    hunger : "πείνα",
    duration : "διάρκεια",
    deficit : "έλλειμμα",
    aclock : "ρολόι συναγερμός\nhh:mm:ss , hh:mm , mm (από τώρα)",
    consnegat : "Η κατανάλωση στο χωριό είναι αρνητική. πόσα λεπτά χρειάζεται απόθεμα?",
    bmove : "μετακίνησε κτίρια",
    neighbors : "γείτονες",
    // settings
    auctions: "Δημοπρασία",
    none : "κανένα",
    auto : "αυτόματο",
    info : "πληροφορίες",
    yourrace : "η φυλή σου",
    speedart : "ταχύτητα αντικειμένου",
    racelist : ['Ρωμαίοι','Τεύτονες','Γαλάτες','Nature','Natars','Egyptians','Huns','detect'],
    cranny : "κίτρινο επίπεδο κρυψώνας (ποσοστό)",
    crannyh : 'κανονικό 80, 70 για κλασικό ή αντικείμενο λεηλασίας',
    builtin : "Ενσωματωμένα εργαλεία",
    builtinh : 'για ομαλοποίηση παραγωγής: κόκκινο χρώμα - μεγαλύτερη ανάγκη πόρων, πράσινο - λιγότερη ανάγκη πόρων',
    normalize : 'ομαλοποίηση παραγωγής',
    normal : "κανονικό",
    banalyze : "ενσωματωμένος αναλυτής μάχης",
    cropfind : "ενσωματωμένη εύρεση πολυσιταρων",
    adetect : "εντοπισμός επίθεσης",
    adetecto : ['ανενεργό','χωρίς ακινητοποίηση','ενεργό'],
    adetecth : "κάνει κρυφά αιτήματα στον εξυπηρετητή, παραβιάζοντας τους κανόνες. μπορεί να οδηγήσει σε τιμωρία.",
    adetectt : "περίοδος εντοπισμού επίθεσης",
    buildhint : "συμβουλή κατασκευής",
    onallp : "όλες οι σελίδες",
    buildand : "εμφάνιση αντίστροφης μέτρησης κτιρίου και επίθεσης",
    buildandh : 'στην λίστα των χωριών',
    sendres : "εμφάνισε «στείλε ύλες/στρατεύματα» εικονίδια",
    sendmess : "εμφάνισε «στείλε μήνυμα» εικονίδιο",
    analyzer : "World analyzer",
    bigicon : "εμφάνισε πλατεία συγκέντρωσης ειδών",
    addvtable : "Εμφάνιση επιπλέον πίνακα χωριών",
    addvtableo : ['ανενεργό','ενεργό','κολλημένο'],
    opennote : "άνοιξε αυτόματα σημειωματάριο",
    notesize : "μέγεθος παράθυρου σημειωματάριου",
    openoview : "άνοιξε αυτόματα την εμφάνιση χωριών",
    resbar : "μπάρα πόρων",
    showres : "εμφάνισε την μπάρα πόρων σε παράθυρο",
    redbl : "κόκκινο (σε ώρες)",
    yellowbl: "κίτρινο (σε ώρες)",
    marketpl : "Αγορά",
    npcsum : "σύνολο για NPC",
    npcsumh : 'στην αγορά και στα κτίρια',
    bidinc : "ανέβασε προσφορά",
    bidinch : 'για περιπέτειες travian4',
    show3x : "μπορεί να εμφανίζει λανθασμένα δεδομένα",
    show3xh : 'πρόβλεψη ροής των πόρων σε 3x και 2x αποστολή',
    rpandmp : "πλατεία συγκέντρωσης και αγορά",
    incomres : "πληροφορίες εισερχόμενων πόρων",
    incomreso : ['ανενεργό','ενεργό','με σύνολο','για θαύμα'],
    troopsI : "πληροφορίες για τα στρατεύματα",
    troopsIo : ['ανενεργό','ενεργό','βοήθεια σάρωσης'],
    defRP : "προεπιλεγμένη ενέργεια για την πλατεία συνέλευσης",
    showls : "εμφάνισε συνδέσμους",
    showAsSN : "χρησιμοποίησε συνδέσμους ως δεύτερο όνομα",
    showlso : ['ανενεργό','ενεργό','σε παράθυρο'],
    savedls : "αποθηκευμένοι σύνδεσμοι",
    savedd : "αποθηκευμένα δεδομένα",
    saveddh : 'συμπεριλαμβανομένων των συνδέσμων και του δεύτερου ονόματος. Αν ένας λογαριασμός διαγραφεί, ή όχι ο υπολογιστής σας.',
    savedelall : "διαγραφή όλων των αποθηκευμένων δεδομένων",
    savedelallh : 'Είστε σίγουρος ότι θέλετε να διαγράψετε όλα τα δεδομένα, συμπεριλαμβανομένων των συνδέσμων και το δεύτερο όνομα?',
    scrlang : "γλώσσα Script",
    youlang : "η γλώσσα σου",
    notifi : "ειδοποίηση",
    notification : "ειδοποίηση μετά την κατασκευή",
    method : "μέθοδος",
    audiourl : "URL για αρχείο ήχου",
    audiotest : "δοκιμή ήχου",
    colorCustomize : "επιλογές χρωμάτων",
    colorHint : "άφησε κενό για προεπιλεγμένο χρώμα",
    color0 : "διαθέσιμη αναβάθμιση",
    color1 : "αναβάθμιση μεσώ NPC",
    color2 : "αναβάθμιση δεν είναι δυνατή <br/>(όχι αρκετοί πόροι)",
    color3 : "αναβάθμιση δεν είναι δυνατή <br/>(όχι αρκετή χωρητικότητα αποθηκών/σιταποθηκών)",
    color4 : "ανώτατο επίπεδο"
  },
  nl: {
    // ingame messages
    ok : "Ok",
    cancel : "Annuleren",
    close : "Sluiten",
    overview : "dorpen overzicht",
    svers : "script versie",
    settings : "instellingen",
    notes : "notities",
    res90 : "grondstoffen voor tot % vullen",
    refresh : "herlaad",
    warehouse : "Warenhuis",
    resources : "Grondstoffen",
    troops : "Troepen",
    links : "Links",
    linkname : "link naam",
    linkdel : "verwijder link",
    name2 : "tweede naam",
    archive : "Archiveer",
    arena : "Toernooiveld",
    addcur : "Voeg huidige toe",
    del : "verwijder",
    edit : "wijzig",
    unpin : "losmaken",
    pin : "vastzetten",
    total : "Totaal",
    noplace : "Er is geen plaats!",
    hunger : "honger",
    duration : "duur",
    deficit : "tekort",
    aclock : "Alarmklok\nhh:mm:ss , hh:mm , mm (van nu)",
    consnegat : "Consumptie in dit dorp is negatief. Hoeveel minuten reserve nodig?",
    bmove : "Verplaats gebouwen",
    neighbors : "buren",
    // settings
    auctions: "Veilingen",
    none : "Geen",
    auto : "automatisch",
    info : "Informatie",
    yourrace : "Jouw ras",
    speedart : "Snelheids artefact",
    racelist : ['Romeinen','Germanen','Galliërs','Nature','Natars','Egyptians','Huns','detect'],
    cranny : "geel niveau van schuilplaats (procent)",
    crannyh : 'normaal 80, 70 voor klassieke servers of artefact plunderen',
    builtin : "Ingebouwde hulpmiddelen",
    builtinh : 'voor normalisatie van productie: rode kleur - meest benodigde grondstoffen, groen - minder benodigde grondstoffen',
    normalize : 'Normalisatie van productie',
    normal : "normaal",
    banalyze : "Ingebouwde gevechts analysator",
    cropfind : "Ingebouwde cropper zoeker",
    adetect : "Detecteer aanval",
    adetecto : ['uit','zonder stilzetten','aan'],
    adetecth : "maakt de verborgen verzoeken aan de server, overtreed de regels. kan in bestraffing resulteren.",
    adetectt : "periode van aanvals detectie",
    buildhint : "Tips voor constructie",
    onallp : "Alle pagina's",
    buildand : "Laat aftelling van gebouwen en aanvallen zien",
    buildandh : 'In de dorpen lijst',
    sendres : "Laat «stuur grondstoffen/troepen» iconen zien",
    sendmess : "Laat «stuur bericht» iconen zien",
    analyzer : "Wereld analysator",
    bigicon : "Laat verzamelplaats icoon zien",
    addvtable : "Laat extra dorpen tabel zien",
    addvtableo : ['uit','aan','vastzetten'],
    opennote : "Automatisch notities openen",
    notesize : "Grootte van scherm voor notities",
    openoview : "Automatisch dorpen overzicht weergeven",
    resbar : "Grondstoffen balk",
    showres : "Laat grondstoffen balk zien in een los scherm",
    redbl : "rood (in uren)",
    yellowbl: "geel (in uren)",
    marketpl : "Marktplaats",
    npcsum : "opsomming voor NPC",
    npcsumh : 'in marktplaats en gebouwen',
    bidinc : "bod toenemening",
    bidinch : 'voor travian4 veilingen',
    show3x : "kan incorrecte data weergeven",
    show3xh : 'probeer de grondstoffenstroom te voorspellen bij 3x en 2x versturen',
    rpandmp : "Verzamelnplaats en Marktplaats",
    incomres : "binnenkomende grondstoffen info",
    incomreso : ['uit','aan','met opsomming','WW modus'],
    troopsI : "Informatie over de troepen",
    troopsIo : ['uit','aan','scan hulp'],
    defRP : "standaard actie voor verzamelplaats",
    showls : "Laat links zien",
    showAsSN : "Gebruik links als tweede naam",
    showlso : ['uit','aan','in apart scherm'],
    savedls : "opgeslagen links",
    savedd : "opgeslagen data",
    saveddh : 'inclusief links en tweede naam. Voor als een account is verwijderd, of dit niet jouw pc is.',
    savedelall : "verwijder alle opgeslagen data",
    savedelallh : 'Weet je zeker dat je alle data wilt verwijderen, inclusief links en tweede naam?',
    scrlang : "Script taal",
    youlang : "jouw taal",
    notifi : "notificatie",
    notification : "notificatie na bouw",
    method : "methode",
    audiourl : "URL van geluidsbestand",
    audiotest : "test geluidsbestand",
    colorCustomize : "Kleuren opties",
    colorHint : "laat leeg voor standaard kleur",
    color0 : "verbetering beschikbaar",
    color1 : "verbetering via NPC",
    color2 : "verbetering niet beschikbaar <br/>(niet genoeg grondstoffen)",
    color3 : "verbetering niet beschikbaar <br/>(niet genoeg capaciteit van warenhuis of graansilo)",
    color4 : "laatste niveau"
  },
  id: {
    // ingame messages
    ok : "OK",
    cancel : "Batal",
    close : "Tutup",
    save : "Simpan",
    reset : "Kembalikan",
    overview : "Tinjauan desa",
    svers : "Versi skrip",
    settings : "Pengaturan",
    notes : "Catatan",
    res90 : "Kurang sda sekian %",
    refresh : "Segarkan",
    warehouse : "Gudang",
    resources : "Sumber daya",
    troops : "Pasukan",
    links : "Pranala",
    linkname : "Nama pranala",
    linkdel : "Hapus pranala",
    name2 : "Nama lain",
    archive : "Arsip",
    arena : "Pusat Kebugaran",
    addcur : "Tambah url saat ini",
    del : "Hapus",
    edit : "Sunting",
    unpin : "Batal semat",
    pin : "Semat",
    total : "Total",
    noplace : "Tidak ada tempat!",
    hunger : "lapar",
    duration : "durasi",
    deficit : "defisit",
    aclock : "Alarm\nhh:mm:ss , hh:mm , mm (dari sekarang)",
    consnegat : "Konsumsi gandum desa negatif. Berapa menit diperlukan cadangan?",
    bmove : "Pindahkan bangunan",
    neighbors : "tetangga",
    // settings
    auctions: "Lelang",
    none : "Tak ada",
    auto : "otomatis",
    info : "Informasi",
    yourrace : "Suku Anda",
    sspeed : "Kecepatan Server",
    sspeedh : "0 - otomatis, 1 (1x), 2 (2x), 3 (3x als speed), ... dll.",
    servertype : "Tipe Travian Server",
    servertypeh : "Tipe Server: Travian Legends, Travian Shadow Empires",
    servertypeo : ['pembaruan','Shadow Empires','Legends'],
    speedart : "Speed artefak",
    racelist : ['Romawi','Teuton','Galia','Alam','Natar','Mesir','Mongol','deteksi'],
    cranny : "Level kuning dari (persen)",
    crannyh : 'normal 80, 70 utk klasik atau penjarahan artefak',
    builtin : "Perkakas bawaan",
    builtinh : 'Merah - sangat perlu sumber daya, Hijau - agak perlu sumber daya',
    normalize : 'Normalkan untuk produksi:',
    normal : "normal",
    banalyze : "Analisa pertempuran bawaan",
    cropfind : "Pencari gandum bawaan",
    adetect : "Pendeteksi serangan",
    adetecto : ['mati','w/o henti','hidup'],
    adetecth : "Membuat permintaan tersembunyi ke server, melanggar aturan. Dapat menyebabkan hukuman.",
    adetectt : "Periode serangan terdeteksi",
    adetectth : "Pemeriksaan awal selalu setelah 5 menit. Pemeriksaan selanjutnya setelah dikonfigurasi.",
    buildhint : "Tip konstruksi",
    onallp : "Semua halaman",
    buildand : "Tampilkan tanda sedang dibangun dan serangan",
    buildandh : 'Dalam daftar desa',
    buildands : ['mati','hidup','lebar'],
    sendres : "Tampilkan ikon &laquo;kirim sumber daya/pasukan&raquo;",
    sendmess : "Tampilkan ikon &laquo;kirim pesan&raquo;",
    analyzer : "Penganalisa Wilayah",
    bigicon : "Tampilkan ikon Titik Temu",
    addvtable : "Tampilkan tabel desa tambahan",
    addvtableo : ['mati','hidup','centang'],
    opennote : "Otomatis membuka jendela Catatan",
    notesize : "Ukuran jendela Catatan",
    openoview : "Otomatis membuka tinjauan desa",
    resbar : "Bilah sumber daya",
    showres : "Tampilkan bilah sumber daya di jendela",
    redbl : "Merah (jam)",
    yellowbl: "Kuning  (jam)",
    marketpl : "Pasar",
    npcsum : "Ringkasan untuk NPC",
    npcsumh : 'Di pasar dan bangunan',
    bidinc : "Jumlah kenaikan tawaran lelang",
    bidinch : 'Masukkan nilai 0 untuk menonaktifkan fungsi',
    show3x : "Prediksi jumlah sumber daya saat dikirim bersama 2x dan 3x",
    show3xh : 'dapat menampilkan data yang salah',
    rpandmp : "Titik Temu dan Pasar",
    incomres : "Info sumber daya masuk",
    incomreso : ['mati','hidup','dengan ringkasan','mode WW'],
    troopsI : "Informasi tentang pasukan",
    troopsIo : ['mati','hidup','pembaruan'],
    defRP : "Tindakan baku utk Titik Temu",
    showls : "Tampilkan pranala",
    showAsSN : "Gunakan pranala sebagai nama lain",
    showlso : ['mati','hidup','di jendela'],
    savedls : "Simpan pranala",
    savedd : "Simpan data",
    saveddh : 'Termasuk Pranala dan Nama lain. Jika Akun dihapus, atau bukan komputer Anda.',
    savedelall : "Hapus semua data yang disimpan",
    savedelallh : 'Anda yakin ingin menghapus semua data, termasuk pranala  dan nama lain?',
    scrlang : "Bahasa skrip",
    youlang : "Bahasa peramban",
    notifi : "Pemberitahuan",
    notification : "Pemberitahuan setelah pembangunan",
    method : "Metode",
    audiourl : "URL file audio",
    audiotest : "Tes audio",
    colorCustomize : "Pilihan warna",
    colorHint : "Biarkan kosong utk warna baku",
    color0 : "Tersedia peningkatan",
    color1 : "Tingkatkan via NPC",
    color2 : "Tak dapat ditingkatkan<br/>(tak cukup sumber daya)",
    color3 : "Tak dapat ditingkatkan<br/>(tak cukup kapasitas lumbung/gudang)",
    color4 : "Level terakhir"
  }
});